
export enum access_analyzer {
 All = 'access-analyzer:*',
 Create = 'access-analyzer:Create*',
 Delete = 'access-analyzer:Delete*',
 Get = 'access-analyzer:Get*',
 List = 'access-analyzer:List*',
 Update = 'access-analyzer:Update*',
 ApplyArchiveRule = 'access-analyzer:ApplyArchiveRule',
 CreateAnalyzer = 'access-analyzer:CreateAnalyzer',
 CreateArchiveRule = 'access-analyzer:CreateArchiveRule',
 DeleteAnalyzer = 'access-analyzer:DeleteAnalyzer',
 DeleteArchiveRule = 'access-analyzer:DeleteArchiveRule',
 GetAnalyzedResource = 'access-analyzer:GetAnalyzedResource',
 GetAnalyzer = 'access-analyzer:GetAnalyzer',
 GetArchiveRule = 'access-analyzer:GetArchiveRule',
 GetFinding = 'access-analyzer:GetFinding',
 ListAnalyzedResources = 'access-analyzer:ListAnalyzedResources',
 ListAnalyzers = 'access-analyzer:ListAnalyzers',
 ListArchiveRules = 'access-analyzer:ListArchiveRules',
 ListFindings = 'access-analyzer:ListFindings',
 ListTagsForResource = 'access-analyzer:ListTagsForResource',
 StartResourceScan = 'access-analyzer:StartResourceScan',
 TagResource = 'access-analyzer:TagResource',
 UntagResource = 'access-analyzer:UntagResource',
 UpdateArchiveRule = 'access-analyzer:UpdateArchiveRule',
 UpdateFindings = 'access-analyzer:UpdateFindings',

}