
export enum amplify {
 CreateApp = 'amplify:CreateApp',
 CreateBackendEnvironment = 'amplify:CreateBackendEnvironment',
 CreateBranch = 'amplify:CreateBranch',
 CreateDeployment = 'amplify:CreateDeployment',
 CreateDomainAssociation = 'amplify:CreateDomainAssociation',
 CreateWebHook = 'amplify:CreateWebHook',
 DeleteApp = 'amplify:DeleteApp',
 DeleteBackendEnvironment = 'amplify:DeleteBackendEnvironment',
 DeleteBranch = 'amplify:DeleteBranch',
 DeleteDomainAssociation = 'amplify:DeleteDomainAssociation',
 DeleteJob = 'amplify:DeleteJob',
 DeleteWebHook = 'amplify:DeleteWebHook',
 GenerateAccessLogs = 'amplify:GenerateAccessLogs',
 GetApp = 'amplify:GetApp',
 GetArtifactUrl = 'amplify:GetArtifactUrl',
 GetBackendEnvironment = 'amplify:GetBackendEnvironment',
 GetBranch = 'amplify:GetBranch',
 GetDomainAssociation = 'amplify:GetDomainAssociation',
 GetJob = 'amplify:GetJob',
 GetWebHook = 'amplify:GetWebHook',
 ListApps = 'amplify:ListApps',
 ListArtifacts = 'amplify:ListArtifacts',
 ListBackendEnvironments = 'amplify:ListBackendEnvironments',
 ListBranches = 'amplify:ListBranches',
 ListDomainAssociations = 'amplify:ListDomainAssociations',
 ListJobs = 'amplify:ListJobs',
 ListWebHooks = 'amplify:ListWebHooks',
 StartDeployment = 'amplify:StartDeployment',
 StartJob = 'amplify:StartJob',
 StopJob = 'amplify:StopJob',
 TagResource = 'amplify:TagResource',
 UntagResource = 'amplify:UntagResource',
 UpdateApp = 'amplify:UpdateApp',
 UpdateBranch = 'amplify:UpdateBranch',
 UpdateDomainAssociation = 'amplify:UpdateDomainAssociation',
 UpdateWebHook = 'amplify:UpdateWebHook',

}