
export enum appconfig {
 All = 'appconfig:*',
 Create = 'appconfig:Create*',
 Delete = 'appconfig:Delete*',
 Get = 'appconfig:Get*',
 List = 'appconfig:List*',
 Update = 'appconfig:Update*',
 CreateApplication = 'appconfig:CreateApplication',
 CreateConfigurationProfile = 'appconfig:CreateConfigurationProfile',
 CreateDeploymentStrategy = 'appconfig:CreateDeploymentStrategy',
 CreateEnvironment = 'appconfig:CreateEnvironment',
 CreateHostedConfigurationVersion = 'appconfig:CreateHostedConfigurationVersion',
 DeleteApplication = 'appconfig:DeleteApplication',
 DeleteConfigurationProfile = 'appconfig:DeleteConfigurationProfile',
 DeleteDeploymentStrategy = 'appconfig:DeleteDeploymentStrategy',
 DeleteEnvironment = 'appconfig:DeleteEnvironment',
 DeleteHostedConfigurationVersion = 'appconfig:DeleteHostedConfigurationVersion',
 GetApplication = 'appconfig:GetApplication',
 GetConfiguration = 'appconfig:GetConfiguration',
 GetConfigurationProfile = 'appconfig:GetConfigurationProfile',
 GetDeployment = 'appconfig:GetDeployment',
 GetDeploymentStrategy = 'appconfig:GetDeploymentStrategy',
 GetEnvironment = 'appconfig:GetEnvironment',
 GetHostedConfigurationVersion = 'appconfig:GetHostedConfigurationVersion',
 ListApplications = 'appconfig:ListApplications',
 ListConfigurationProfiles = 'appconfig:ListConfigurationProfiles',
 ListDeploymentStrategies = 'appconfig:ListDeploymentStrategies',
 ListDeployments = 'appconfig:ListDeployments',
 ListEnvironments = 'appconfig:ListEnvironments',
 ListHostedConfigurationVersions = 'appconfig:ListHostedConfigurationVersions',
 ListTagsForResource = 'appconfig:ListTagsForResource',
 StartDeployment = 'appconfig:StartDeployment',
 StopDeployment = 'appconfig:StopDeployment',
 TagResource = 'appconfig:TagResource',
 UntagResource = 'appconfig:UntagResource',
 UpdateApplication = 'appconfig:UpdateApplication',
 UpdateConfigurationProfile = 'appconfig:UpdateConfigurationProfile',
 UpdateDeploymentStrategy = 'appconfig:UpdateDeploymentStrategy',
 UpdateEnvironment = 'appconfig:UpdateEnvironment',
 ValidateConfiguration = 'appconfig:ValidateConfiguration',

}