
export enum applicationinsights {
 CreateApplication = 'applicationinsights:CreateApplication',
 CreateComponent = 'applicationinsights:CreateComponent',
 CreateLogPattern = 'applicationinsights:CreateLogPattern',
 DeleteApplication = 'applicationinsights:DeleteApplication',
 DeleteComponent = 'applicationinsights:DeleteComponent',
 DeleteLogPattern = 'applicationinsights:DeleteLogPattern',
 DescribeApplication = 'applicationinsights:DescribeApplication',
 DescribeComponent = 'applicationinsights:DescribeComponent',
 DescribeComponentConfiguration = 'applicationinsights:DescribeComponentConfiguration',
 DescribeComponentConfigurationRecommendation = 'applicationinsights:DescribeComponentConfigurationRecommendation',
 DescribeLogPattern = 'applicationinsights:DescribeLogPattern',
 DescribeObservation = 'applicationinsights:DescribeObservation',
 DescribeProblem = 'applicationinsights:DescribeProblem',
 DescribeProblemObservations = 'applicationinsights:DescribeProblemObservations',
 ListApplications = 'applicationinsights:ListApplications',
 ListComponents = 'applicationinsights:ListComponents',
 ListConfigurationHistory = 'applicationinsights:ListConfigurationHistory',
 ListLogPatternSets = 'applicationinsights:ListLogPatternSets',
 ListLogPatterns = 'applicationinsights:ListLogPatterns',
 ListProblems = 'applicationinsights:ListProblems',
 ListTagsForResource = 'applicationinsights:ListTagsForResource',
 TagResource = 'applicationinsights:TagResource',
 UntagResource = 'applicationinsights:UntagResource',
 UpdateApplication = 'applicationinsights:UpdateApplication',
 UpdateComponent = 'applicationinsights:UpdateComponent',
 UpdateComponentConfiguration = 'applicationinsights:UpdateComponentConfiguration',
 UpdateLogPattern = 'applicationinsights:UpdateLogPattern',

}