
export enum appmesh {
 CreateGatewayRoute = 'appmesh:CreateGatewayRoute',
 CreateMesh = 'appmesh:CreateMesh',
 CreateRoute = 'appmesh:CreateRoute',
 CreateVirtualGateway = 'appmesh:CreateVirtualGateway',
 CreateVirtualNode = 'appmesh:CreateVirtualNode',
 CreateVirtualRouter = 'appmesh:CreateVirtualRouter',
 CreateVirtualService = 'appmesh:CreateVirtualService',
 DeleteGatewayRoute = 'appmesh:DeleteGatewayRoute',
 DeleteMesh = 'appmesh:DeleteMesh',
 DeleteRoute = 'appmesh:DeleteRoute',
 DeleteVirtualGateway = 'appmesh:DeleteVirtualGateway',
 DeleteVirtualNode = 'appmesh:DeleteVirtualNode',
 DeleteVirtualRouter = 'appmesh:DeleteVirtualRouter',
 DeleteVirtualService = 'appmesh:DeleteVirtualService',
 DescribeGatewayRoute = 'appmesh:DescribeGatewayRoute',
 DescribeMesh = 'appmesh:DescribeMesh',
 DescribeRoute = 'appmesh:DescribeRoute',
 DescribeVirtualGateway = 'appmesh:DescribeVirtualGateway',
 DescribeVirtualNode = 'appmesh:DescribeVirtualNode',
 DescribeVirtualRouter = 'appmesh:DescribeVirtualRouter',
 DescribeVirtualService = 'appmesh:DescribeVirtualService',
 ListGatewayRoutes = 'appmesh:ListGatewayRoutes',
 ListMeshes = 'appmesh:ListMeshes',
 ListRoutes = 'appmesh:ListRoutes',
 ListTagsForResource = 'appmesh:ListTagsForResource',
 ListVirtualGateways = 'appmesh:ListVirtualGateways',
 ListVirtualNodes = 'appmesh:ListVirtualNodes',
 ListVirtualRouters = 'appmesh:ListVirtualRouters',
 ListVirtualServices = 'appmesh:ListVirtualServices',
 StreamAggregatedResources = 'appmesh:StreamAggregatedResources',
 TagResource = 'appmesh:TagResource',
 UntagResource = 'appmesh:UntagResource',
 UpdateGatewayRoute = 'appmesh:UpdateGatewayRoute',
 UpdateMesh = 'appmesh:UpdateMesh',
 UpdateRoute = 'appmesh:UpdateRoute',
 UpdateVirtualGateway = 'appmesh:UpdateVirtualGateway',
 UpdateVirtualNode = 'appmesh:UpdateVirtualNode',
 UpdateVirtualRouter = 'appmesh:UpdateVirtualRouter',
 UpdateVirtualService = 'appmesh:UpdateVirtualService',

}