
export enum appmesh_preview {
 CreateGatewayRoute = 'appmesh-preview:CreateGatewayRoute',
 CreateMesh = 'appmesh-preview:CreateMesh',
 CreateRoute = 'appmesh-preview:CreateRoute',
 CreateVirtualGateway = 'appmesh-preview:CreateVirtualGateway',
 CreateVirtualNode = 'appmesh-preview:CreateVirtualNode',
 CreateVirtualRouter = 'appmesh-preview:CreateVirtualRouter',
 CreateVirtualService = 'appmesh-preview:CreateVirtualService',
 DeleteGatewayRoute = 'appmesh-preview:DeleteGatewayRoute',
 DeleteMesh = 'appmesh-preview:DeleteMesh',
 DeleteRoute = 'appmesh-preview:DeleteRoute',
 DeleteVirtualGateway = 'appmesh-preview:DeleteVirtualGateway',
 DeleteVirtualNode = 'appmesh-preview:DeleteVirtualNode',
 DeleteVirtualRouter = 'appmesh-preview:DeleteVirtualRouter',
 DeleteVirtualService = 'appmesh-preview:DeleteVirtualService',
 DescribeGatewayRoute = 'appmesh-preview:DescribeGatewayRoute',
 DescribeMesh = 'appmesh-preview:DescribeMesh',
 DescribeRoute = 'appmesh-preview:DescribeRoute',
 DescribeVirtualGateway = 'appmesh-preview:DescribeVirtualGateway',
 DescribeVirtualNode = 'appmesh-preview:DescribeVirtualNode',
 DescribeVirtualRouter = 'appmesh-preview:DescribeVirtualRouter',
 DescribeVirtualService = 'appmesh-preview:DescribeVirtualService',
 ListGatewayRoutes = 'appmesh-preview:ListGatewayRoutes',
 ListMeshes = 'appmesh-preview:ListMeshes',
 ListRoutes = 'appmesh-preview:ListRoutes',
 ListVirtualGateways = 'appmesh-preview:ListVirtualGateways',
 ListVirtualNodes = 'appmesh-preview:ListVirtualNodes',
 ListVirtualRouters = 'appmesh-preview:ListVirtualRouters',
 ListVirtualServices = 'appmesh-preview:ListVirtualServices',
 StreamAggregatedResources = 'appmesh-preview:StreamAggregatedResources',
 UpdateGatewayRoute = 'appmesh-preview:UpdateGatewayRoute',
 UpdateMesh = 'appmesh-preview:UpdateMesh',
 UpdateRoute = 'appmesh-preview:UpdateRoute',
 UpdateVirtualGateway = 'appmesh-preview:UpdateVirtualGateway',
 UpdateVirtualNode = 'appmesh-preview:UpdateVirtualNode',
 UpdateVirtualRouter = 'appmesh-preview:UpdateVirtualRouter',
 UpdateVirtualService = 'appmesh-preview:UpdateVirtualService',

}