
export enum appsync {
 CreateApiKey = 'appsync:CreateApiKey',
 CreateDataSource = 'appsync:CreateDataSource',
 CreateFunction = 'appsync:CreateFunction',
 CreateGraphqlApi = 'appsync:CreateGraphqlApi',
 CreateResolver = 'appsync:CreateResolver',
 CreateType = 'appsync:CreateType',
 DeleteApiKey = 'appsync:DeleteApiKey',
 DeleteDataSource = 'appsync:DeleteDataSource',
 DeleteFunction = 'appsync:DeleteFunction',
 DeleteGraphqlApi = 'appsync:DeleteGraphqlApi',
 DeleteResolver = 'appsync:DeleteResolver',
 DeleteType = 'appsync:DeleteType',
 GetDataSource = 'appsync:GetDataSource',
 GetFunction = 'appsync:GetFunction',
 GetGraphqlApi = 'appsync:GetGraphqlApi',
 GetIntrospectionSchema = 'appsync:GetIntrospectionSchema',
 GetResolver = 'appsync:GetResolver',
 GetSchemaCreationStatus = 'appsync:GetSchemaCreationStatus',
 GetType = 'appsync:GetType',
 GraphQL = 'appsync:GraphQL',
 ListApiKeys = 'appsync:ListApiKeys',
 ListDataSources = 'appsync:ListDataSources',
 ListFunctions = 'appsync:ListFunctions',
 ListGraphqlApis = 'appsync:ListGraphqlApis',
 ListResolvers = 'appsync:ListResolvers',
 ListResolversByFunction = 'appsync:ListResolversByFunction',
 ListTagsForResource = 'appsync:ListTagsForResource',
 ListTypes = 'appsync:ListTypes',
 SetWebACL = 'appsync:SetWebACL',
 StartSchemaCreation = 'appsync:StartSchemaCreation',
 TagResource = 'appsync:TagResource',
 UntagResource = 'appsync:UntagResource',
 UpdateApiKey = 'appsync:UpdateApiKey',
 UpdateDataSource = 'appsync:UpdateDataSource',
 UpdateFunction = 'appsync:UpdateFunction',
 UpdateGraphqlApi = 'appsync:UpdateGraphqlApi',
 UpdateResolver = 'appsync:UpdateResolver',
 UpdateType = 'appsync:UpdateType',

}