
export enum athena {
 BatchGetNamedQuery = 'athena:BatchGetNamedQuery',
 BatchGetQueryExecution = 'athena:BatchGetQueryExecution',
 CreateDataCatalog = 'athena:CreateDataCatalog',
 CreateNamedQuery = 'athena:CreateNamedQuery',
 CreateWorkGroup = 'athena:CreateWorkGroup',
 DeleteDataCatalog = 'athena:DeleteDataCatalog',
 DeleteNamedQuery = 'athena:DeleteNamedQuery',
 DeleteWorkGroup = 'athena:DeleteWorkGroup',
 GetDataCatalog = 'athena:GetDataCatalog',
 GetDatabase = 'athena:GetDatabase',
 GetNamedQuery = 'athena:GetNamedQuery',
 GetQueryExecution = 'athena:GetQueryExecution',
 GetQueryResults = 'athena:GetQueryResults',
 GetQueryResultsStream = 'athena:GetQueryResultsStream',
 GetTableMetadata = 'athena:GetTableMetadata',
 GetWorkGroup = 'athena:GetWorkGroup',
 ListDataCatalogs = 'athena:ListDataCatalogs',
 ListDatabases = 'athena:ListDatabases',
 ListEngineVersions = 'athena:ListEngineVersions',
 ListNamedQueries = 'athena:ListNamedQueries',
 ListQueryExecutions = 'athena:ListQueryExecutions',
 ListTableMetadata = 'athena:ListTableMetadata',
 ListTagsForResource = 'athena:ListTagsForResource',
 ListWorkGroups = 'athena:ListWorkGroups',
 StartQueryExecution = 'athena:StartQueryExecution',
 StopQueryExecution = 'athena:StopQueryExecution',
 TagResource = 'athena:TagResource',
 UntagResource = 'athena:UntagResource',
 UpdateDataCatalog = 'athena:UpdateDataCatalog',
 UpdateWorkGroup = 'athena:UpdateWorkGroup',

}