
export enum cloudsearch {
 AddTags = 'cloudsearch:AddTags',
 BuildSuggesters = 'cloudsearch:BuildSuggesters',
 CreateDomain = 'cloudsearch:CreateDomain',
 DefineAnalysisScheme = 'cloudsearch:DefineAnalysisScheme',
 DefineExpression = 'cloudsearch:DefineExpression',
 DefineIndexField = 'cloudsearch:DefineIndexField',
 DefineSuggester = 'cloudsearch:DefineSuggester',
 DeleteAnalysisScheme = 'cloudsearch:DeleteAnalysisScheme',
 DeleteDomain = 'cloudsearch:DeleteDomain',
 DeleteExpression = 'cloudsearch:DeleteExpression',
 DeleteIndexField = 'cloudsearch:DeleteIndexField',
 DeleteSuggester = 'cloudsearch:DeleteSuggester',
 DescribeAnalysisSchemes = 'cloudsearch:DescribeAnalysisSchemes',
 DescribeAvailabilityOptions = 'cloudsearch:DescribeAvailabilityOptions',
 DescribeDomainEndpointOptions = 'cloudsearch:DescribeDomainEndpointOptions',
 DescribeDomains = 'cloudsearch:DescribeDomains',
 DescribeExpressions = 'cloudsearch:DescribeExpressions',
 DescribeIndexFields = 'cloudsearch:DescribeIndexFields',
 DescribeScalingParameters = 'cloudsearch:DescribeScalingParameters',
 DescribeServiceAccessPolicies = 'cloudsearch:DescribeServiceAccessPolicies',
 DescribeSuggesters = 'cloudsearch:DescribeSuggesters',
 IndexDocuments = 'cloudsearch:IndexDocuments',
 ListDomainNames = 'cloudsearch:ListDomainNames',
 ListTags = 'cloudsearch:ListTags',
 RemoveTags = 'cloudsearch:RemoveTags',
 UpdateAvailabilityOptions = 'cloudsearch:UpdateAvailabilityOptions',
 UpdateDomainEndpointOptions = 'cloudsearch:UpdateDomainEndpointOptions',
 UpdateScalingParameters = 'cloudsearch:UpdateScalingParameters',
 UpdateServiceAccessPolicies = 'cloudsearch:UpdateServiceAccessPolicies',
 document = 'cloudsearch:document',
 search = 'cloudsearch:search',
 suggest = 'cloudsearch:suggest',

}