
export enum cloudhsm {
 AddTagsToResource = 'cloudhsm:AddTagsToResource',
 CopyBackupToRegion = 'cloudhsm:CopyBackupToRegion',
 CreateCluster = 'cloudhsm:CreateCluster',
 CreateHapg = 'cloudhsm:CreateHapg',
 CreateHsm = 'cloudhsm:CreateHsm',
 CreateLunaClient = 'cloudhsm:CreateLunaClient',
 DeleteBackup = 'cloudhsm:DeleteBackup',
 DeleteCluster = 'cloudhsm:DeleteCluster',
 DeleteHapg = 'cloudhsm:DeleteHapg',
 DeleteHsm = 'cloudhsm:DeleteHsm',
 DeleteLunaClient = 'cloudhsm:DeleteLunaClient',
 DescribeBackups = 'cloudhsm:DescribeBackups',
 DescribeClusters = 'cloudhsm:DescribeClusters',
 DescribeHapg = 'cloudhsm:DescribeHapg',
 DescribeHsm = 'cloudhsm:DescribeHsm',
 DescribeLunaClient = 'cloudhsm:DescribeLunaClient',
 GetConfig = 'cloudhsm:GetConfig',
 InitializeCluster = 'cloudhsm:InitializeCluster',
 ListAvailableZones = 'cloudhsm:ListAvailableZones',
 ListHapgs = 'cloudhsm:ListHapgs',
 ListHsms = 'cloudhsm:ListHsms',
 ListLunaClients = 'cloudhsm:ListLunaClients',
 ListTags = 'cloudhsm:ListTags',
 ListTagsForResource = 'cloudhsm:ListTagsForResource',
 ModifyHapg = 'cloudhsm:ModifyHapg',
 ModifyHsm = 'cloudhsm:ModifyHsm',
 ModifyLunaClient = 'cloudhsm:ModifyLunaClient',
 RemoveTagsFromResource = 'cloudhsm:RemoveTagsFromResource',
 RestoreBackup = 'cloudhsm:RestoreBackup',
 TagResource = 'cloudhsm:TagResource',
 UntagResource = 'cloudhsm:UntagResource',

}