
export enum cloudwatch {
 All = 'cloudwatch:*',
 Delete = 'cloudwatch:Delete*',
 Describe = 'cloudwatch:Describe*',
 Disable = 'cloudwatch:Disable*',
 Enable = 'cloudwatch:Enable*',
 Get = 'cloudwatch:Get*',
 List = 'cloudwatch:List*',
 Put = 'cloudwatch:Put*',
 DeleteAlarms = 'cloudwatch:DeleteAlarms',
 DeleteAnomalyDetector = 'cloudwatch:DeleteAnomalyDetector',
 DeleteDashboards = 'cloudwatch:DeleteDashboards',
 DeleteInsightRules = 'cloudwatch:DeleteInsightRules',
 DescribeAlarmHistory = 'cloudwatch:DescribeAlarmHistory',
 DescribeAlarms = 'cloudwatch:DescribeAlarms',
 DescribeAlarmsForMetric = 'cloudwatch:DescribeAlarmsForMetric',
 DescribeAnomalyDetectors = 'cloudwatch:DescribeAnomalyDetectors',
 DescribeInsightRules = 'cloudwatch:DescribeInsightRules',
 DisableAlarmActions = 'cloudwatch:DisableAlarmActions',
 DisableInsightRules = 'cloudwatch:DisableInsightRules',
 EnableAlarmActions = 'cloudwatch:EnableAlarmActions',
 EnableInsightRules = 'cloudwatch:EnableInsightRules',
 GetDashboard = 'cloudwatch:GetDashboard',
 GetInsightRuleReport = 'cloudwatch:GetInsightRuleReport',
 GetMetricData = 'cloudwatch:GetMetricData',
 GetMetricStatistics = 'cloudwatch:GetMetricStatistics',
 GetMetricWidgetImage = 'cloudwatch:GetMetricWidgetImage',
 ListDashboards = 'cloudwatch:ListDashboards',
 ListMetrics = 'cloudwatch:ListMetrics',
 ListTagsForResource = 'cloudwatch:ListTagsForResource',
 PutAnomalyDetector = 'cloudwatch:PutAnomalyDetector',
 PutCompositeAlarm = 'cloudwatch:PutCompositeAlarm',
 PutDashboard = 'cloudwatch:PutDashboard',
 PutInsightRule = 'cloudwatch:PutInsightRule',
 PutMetricAlarm = 'cloudwatch:PutMetricAlarm',
 PutMetricData = 'cloudwatch:PutMetricData',
 SetAlarmState = 'cloudwatch:SetAlarmState',
 TagResource = 'cloudwatch:TagResource',
 UntagResource = 'cloudwatch:UntagResource',

}