
export enum cloudtrail {
 All = 'cloudtrail:*',
 Get = 'cloudtrail:Get*',
 List = 'cloudtrail:List*',
 Put = 'cloudtrail:Put*',
 AddTags = 'cloudtrail:AddTags',
 CreateTrail = 'cloudtrail:CreateTrail',
 DeleteTrail = 'cloudtrail:DeleteTrail',
 DescribeTrails = 'cloudtrail:DescribeTrails',
 GetEventSelectors = 'cloudtrail:GetEventSelectors',
 GetInsightSelectors = 'cloudtrail:GetInsightSelectors',
 GetTrail = 'cloudtrail:GetTrail',
 GetTrailStatus = 'cloudtrail:GetTrailStatus',
 ListPublicKeys = 'cloudtrail:ListPublicKeys',
 ListTags = 'cloudtrail:ListTags',
 ListTrails = 'cloudtrail:ListTrails',
 LookupEvents = 'cloudtrail:LookupEvents',
 PutEventSelectors = 'cloudtrail:PutEventSelectors',
 PutInsightSelectors = 'cloudtrail:PutInsightSelectors',
 RemoveTags = 'cloudtrail:RemoveTags',
 StartLogging = 'cloudtrail:StartLogging',
 StopLogging = 'cloudtrail:StopLogging',
 UpdateTrail = 'cloudtrail:UpdateTrail',

}