
export enum cognito_identity {
 CreateIdentityPool = 'cognito-identity:CreateIdentityPool',
 DeleteIdentities = 'cognito-identity:DeleteIdentities',
 DeleteIdentityPool = 'cognito-identity:DeleteIdentityPool',
 DescribeIdentity = 'cognito-identity:DescribeIdentity',
 DescribeIdentityPool = 'cognito-identity:DescribeIdentityPool',
 GetCredentialsForIdentity = 'cognito-identity:GetCredentialsForIdentity',
 GetId = 'cognito-identity:GetId',
 GetIdentityPoolRoles = 'cognito-identity:GetIdentityPoolRoles',
 GetOpenIdToken = 'cognito-identity:GetOpenIdToken',
 GetOpenIdTokenForDeveloperIdentity = 'cognito-identity:GetOpenIdTokenForDeveloperIdentity',
 ListIdentities = 'cognito-identity:ListIdentities',
 ListIdentityPools = 'cognito-identity:ListIdentityPools',
 ListTagsForResource = 'cognito-identity:ListTagsForResource',
 LookupDeveloperIdentity = 'cognito-identity:LookupDeveloperIdentity',
 MergeDeveloperIdentities = 'cognito-identity:MergeDeveloperIdentities',
 SetIdentityPoolRoles = 'cognito-identity:SetIdentityPoolRoles',
 TagResource = 'cognito-identity:TagResource',
 UnlinkDeveloperIdentity = 'cognito-identity:UnlinkDeveloperIdentity',
 UnlinkIdentity = 'cognito-identity:UnlinkIdentity',
 UntagResource = 'cognito-identity:UntagResource',
 UpdateIdentityPool = 'cognito-identity:UpdateIdentityPool',

}