
export enum databrew {
 BatchDeleteRecipeVersion = 'databrew:BatchDeleteRecipeVersion',
 CreateDataset = 'databrew:CreateDataset',
 CreateProfileJob = 'databrew:CreateProfileJob',
 CreateProject = 'databrew:CreateProject',
 CreateRecipe = 'databrew:CreateRecipe',
 CreateRecipeJob = 'databrew:CreateRecipeJob',
 CreateSchedule = 'databrew:CreateSchedule',
 DeleteDataset = 'databrew:DeleteDataset',
 DeleteJob = 'databrew:DeleteJob',
 DeleteProject = 'databrew:DeleteProject',
 DeleteRecipeVersion = 'databrew:DeleteRecipeVersion',
 DeleteSchedule = 'databrew:DeleteSchedule',
 DescribeDataset = 'databrew:DescribeDataset',
 DescribeJob = 'databrew:DescribeJob',
 DescribeJobRun = 'databrew:DescribeJobRun',
 DescribeProject = 'databrew:DescribeProject',
 DescribeRecipe = 'databrew:DescribeRecipe',
 DescribeSchedule = 'databrew:DescribeSchedule',
 ListDatasets = 'databrew:ListDatasets',
 ListJobRuns = 'databrew:ListJobRuns',
 ListJobs = 'databrew:ListJobs',
 ListProjects = 'databrew:ListProjects',
 ListRecipeVersions = 'databrew:ListRecipeVersions',
 ListRecipes = 'databrew:ListRecipes',
 ListSchedules = 'databrew:ListSchedules',
 ListTagsForResource = 'databrew:ListTagsForResource',
 PublishRecipe = 'databrew:PublishRecipe',
 SendProjectSessionAction = 'databrew:SendProjectSessionAction',
 StartJobRun = 'databrew:StartJobRun',
 StartProjectSession = 'databrew:StartProjectSession',
 StopJobRun = 'databrew:StopJobRun',
 TagResource = 'databrew:TagResource',
 UntagResource = 'databrew:UntagResource',
 UpdateDataset = 'databrew:UpdateDataset',
 UpdateProfileJob = 'databrew:UpdateProfileJob',
 UpdateProject = 'databrew:UpdateProject',
 UpdateRecipe = 'databrew:UpdateRecipe',
 UpdateRecipeJob = 'databrew:UpdateRecipeJob',
 UpdateSchedule = 'databrew:UpdateSchedule',

}