
export enum datasync {
 CancelTaskExecution = 'datasync:CancelTaskExecution',
 CreateAgent = 'datasync:CreateAgent',
 CreateLocationEfs = 'datasync:CreateLocationEfs',
 CreateLocationFsxWindows = 'datasync:CreateLocationFsxWindows',
 CreateLocationNfs = 'datasync:CreateLocationNfs',
 CreateLocationObjectStorage = 'datasync:CreateLocationObjectStorage',
 CreateLocationS3 = 'datasync:CreateLocationS3',
 CreateLocationSmb = 'datasync:CreateLocationSmb',
 CreateTask = 'datasync:CreateTask',
 DeleteAgent = 'datasync:DeleteAgent',
 DeleteLocation = 'datasync:DeleteLocation',
 DeleteTask = 'datasync:DeleteTask',
 DescribeAgent = 'datasync:DescribeAgent',
 DescribeLocationEfs = 'datasync:DescribeLocationEfs',
 DescribeLocationFsxWindows = 'datasync:DescribeLocationFsxWindows',
 DescribeLocationNfs = 'datasync:DescribeLocationNfs',
 DescribeLocationObjectStorage = 'datasync:DescribeLocationObjectStorage',
 DescribeLocationS3 = 'datasync:DescribeLocationS3',
 DescribeLocationSmb = 'datasync:DescribeLocationSmb',
 DescribeTask = 'datasync:DescribeTask',
 DescribeTaskExecution = 'datasync:DescribeTaskExecution',
 ListAgents = 'datasync:ListAgents',
 ListLocations = 'datasync:ListLocations',
 ListTagsForResource = 'datasync:ListTagsForResource',
 ListTaskExecutions = 'datasync:ListTaskExecutions',
 ListTasks = 'datasync:ListTasks',
 StartTaskExecution = 'datasync:StartTaskExecution',
 TagResource = 'datasync:TagResource',
 UntagResource = 'datasync:UntagResource',
 UpdateAgent = 'datasync:UpdateAgent',
 UpdateTask = 'datasync:UpdateTask',

}