
export enum dax {
 All = 'dax:*',
 Batch = 'dax:Batch*',
 Create = 'dax:Create*',
 Delete = 'dax:Delete*',
 Describe = 'dax:Describe*',
 Update = 'dax:Update*',
 BatchGetItem = 'dax:BatchGetItem',
 BatchWriteItem = 'dax:BatchWriteItem',
 ConditionCheckItem = 'dax:ConditionCheckItem',
 CreateCluster = 'dax:CreateCluster',
 CreateParameterGroup = 'dax:CreateParameterGroup',
 CreateSubnetGroup = 'dax:CreateSubnetGroup',
 DecreaseReplicationFactor = 'dax:DecreaseReplicationFactor',
 DeleteCluster = 'dax:DeleteCluster',
 DeleteItem = 'dax:DeleteItem',
 DeleteParameterGroup = 'dax:DeleteParameterGroup',
 DeleteSubnetGroup = 'dax:DeleteSubnetGroup',
 DescribeClusters = 'dax:DescribeClusters',
 DescribeDefaultParameters = 'dax:DescribeDefaultParameters',
 DescribeEvents = 'dax:DescribeEvents',
 DescribeParameterGroups = 'dax:DescribeParameterGroups',
 DescribeParameters = 'dax:DescribeParameters',
 DescribeSubnetGroups = 'dax:DescribeSubnetGroups',
 GetItem = 'dax:GetItem',
 IncreaseReplicationFactor = 'dax:IncreaseReplicationFactor',
 ListTags = 'dax:ListTags',
 PutItem = 'dax:PutItem',
 Query = 'dax:Query',
 RebootNode = 'dax:RebootNode',
 Scan = 'dax:Scan',
 TagResource = 'dax:TagResource',
 UntagResource = 'dax:UntagResource',
 UpdateCluster = 'dax:UpdateCluster',
 UpdateItem = 'dax:UpdateItem',
 UpdateParameterGroup = 'dax:UpdateParameterGroup',
 UpdateSubnetGroup = 'dax:UpdateSubnetGroup',

}