
export enum deepcomposer {
 All = 'deepcomposer:*',
 Create = 'deepcomposer:Create*',
 Delete = 'deepcomposer:Delete*',
 Get = 'deepcomposer:Get*',
 List = 'deepcomposer:List*',
 Update = 'deepcomposer:Update*',
 AssociateCoupon = 'deepcomposer:AssociateCoupon',
 CreateAudio = 'deepcomposer:CreateAudio',
 CreateComposition = 'deepcomposer:CreateComposition',
 CreateModel = 'deepcomposer:CreateModel',
 DeleteComposition = 'deepcomposer:DeleteComposition',
 DeleteModel = 'deepcomposer:DeleteModel',
 GetComposition = 'deepcomposer:GetComposition',
 GetModel = 'deepcomposer:GetModel',
 GetSampleModel = 'deepcomposer:GetSampleModel',
 ListCompositions = 'deepcomposer:ListCompositions',
 ListModels = 'deepcomposer:ListModels',
 ListSampleModels = 'deepcomposer:ListSampleModels',
 ListTagsForResource = 'deepcomposer:ListTagsForResource',
 ListTrainingTopics = 'deepcomposer:ListTrainingTopics',
 TagResource = 'deepcomposer:TagResource',
 UntagResource = 'deepcomposer:UntagResource',
 UpdateComposition = 'deepcomposer:UpdateComposition',
 UpdateModel = 'deepcomposer:UpdateModel',

}