
export enum deepracer {
 CloneReinforcementLearningModel = 'deepracer:CloneReinforcementLearningModel',
 CreateAccountResources = 'deepracer:CreateAccountResources',
 CreateLeaderboardSubmission = 'deepracer:CreateLeaderboardSubmission',
 CreateReinforcementLearningModel = 'deepracer:CreateReinforcementLearningModel',
 DeleteAccountResources = 'deepracer:DeleteAccountResources',
 DeleteModel = 'deepracer:DeleteModel',
 GetAccountResources = 'deepracer:GetAccountResources',
 GetAlias = 'deepracer:GetAlias',
 GetEvaluation = 'deepracer:GetEvaluation',
 GetLatestUserSubmission = 'deepracer:GetLatestUserSubmission',
 GetLeaderboard = 'deepracer:GetLeaderboard',
 GetModel = 'deepracer:GetModel',
 GetRankedUserSubmission = 'deepracer:GetRankedUserSubmission',
 GetTrack = 'deepracer:GetTrack',
 GetTrainingJob = 'deepracer:GetTrainingJob',
 ListEvaluations = 'deepracer:ListEvaluations',
 ListLeaderboardSubmissions = 'deepracer:ListLeaderboardSubmissions',
 ListLeaderboards = 'deepracer:ListLeaderboards',
 ListModels = 'deepracer:ListModels',
 ListTracks = 'deepracer:ListTracks',
 ListTrainingJobs = 'deepracer:ListTrainingJobs',
 SetAlias = 'deepracer:SetAlias',
 StartEvaluation = 'deepracer:StartEvaluation',
 StopEvaluation = 'deepracer:StopEvaluation',
 StopTrainingReinforcementLearningModel = 'deepracer:StopTrainingReinforcementLearningModel',
 TestRewardFunction = 'deepracer:TestRewardFunction',

}