
export enum detective {
 All = 'detective:*',
 Create = 'detective:Create*',
 Delete = 'detective:Delete*',
 Get = 'detective:Get*',
 List = 'detective:List*',
 AcceptInvitation = 'detective:AcceptInvitation',
 CreateGraph = 'detective:CreateGraph',
 CreateMembers = 'detective:CreateMembers',
 DeleteGraph = 'detective:DeleteGraph',
 DeleteMembers = 'detective:DeleteMembers',
 DisassociateMembership = 'detective:DisassociateMembership',
 GetFreeTrialEligibility = 'detective:GetFreeTrialEligibility',
 GetGraphIngestState = 'detective:GetGraphIngestState',
 GetMembers = 'detective:GetMembers',
 GetPricingInformation = 'detective:GetPricingInformation',
 GetUsageInformation = 'detective:GetUsageInformation',
 ListGraphs = 'detective:ListGraphs',
 ListInvitations = 'detective:ListInvitations',
 ListMembers = 'detective:ListMembers',
 RejectInvitation = 'detective:RejectInvitation',
 SearchGraph = 'detective:SearchGraph',
 StartMonitoringMember = 'detective:StartMonitoringMember',

}