
export enum devops_guru {
 All = 'devops-guru:*',
 Describe = 'devops-guru:Describe*',
 List = 'devops-guru:List*',
 Update = 'devops-guru:Update*',
 AddNotificationChannel = 'devops-guru:AddNotificationChannel',
 DescribeAccountHealth = 'devops-guru:DescribeAccountHealth',
 DescribeAccountOverview = 'devops-guru:DescribeAccountOverview',
 DescribeAnomaly = 'devops-guru:DescribeAnomaly',
 DescribeInsight = 'devops-guru:DescribeInsight',
 DescribeResourceCollectionHealth = 'devops-guru:DescribeResourceCollectionHealth',
 DescribeServiceIntegration = 'devops-guru:DescribeServiceIntegration',
 GetResourceCollection = 'devops-guru:GetResourceCollection',
 ListAnomaliesForInsight = 'devops-guru:ListAnomaliesForInsight',
 ListEvents = 'devops-guru:ListEvents',
 ListInsights = 'devops-guru:ListInsights',
 ListNotificationChannels = 'devops-guru:ListNotificationChannels',
 ListRecommendations = 'devops-guru:ListRecommendations',
 PutFeedback = 'devops-guru:PutFeedback',
 RemoveNotificationChannel = 'devops-guru:RemoveNotificationChannel',
 SearchInsights = 'devops-guru:SearchInsights',
 UpdateResourceCollection = 'devops-guru:UpdateResourceCollection',
 UpdateServiceIntegration = 'devops-guru:UpdateServiceIntegration',

}