
export enum discovery {
 All = 'discovery:*',
 Create = 'discovery:Create*',
 Delete = 'discovery:Delete*',
 Describe = 'discovery:Describe*',
 List = 'discovery:List*',
 Start = 'discovery:Start*',
 Stop = 'discovery:Stop*',
 AssociateConfigurationItemsToApplication = 'discovery:AssociateConfigurationItemsToApplication',
 BatchDeleteImportData = 'discovery:BatchDeleteImportData',
 CreateApplication = 'discovery:CreateApplication',
 CreateTags = 'discovery:CreateTags',
 DeleteApplications = 'discovery:DeleteApplications',
 DeleteTags = 'discovery:DeleteTags',
 DescribeAgents = 'discovery:DescribeAgents',
 DescribeConfigurations = 'discovery:DescribeConfigurations',
 DescribeContinuousExports = 'discovery:DescribeContinuousExports',
 DescribeExportConfigurations = 'discovery:DescribeExportConfigurations',
 DescribeExportTasks = 'discovery:DescribeExportTasks',
 DescribeImportTasks = 'discovery:DescribeImportTasks',
 DescribeTags = 'discovery:DescribeTags',
 DisassociateConfigurationItemsFromApplication = 'discovery:DisassociateConfigurationItemsFromApplication',
 ExportConfigurations = 'discovery:ExportConfigurations',
 GetDiscoverySummary = 'discovery:GetDiscoverySummary',
 ListConfigurations = 'discovery:ListConfigurations',
 ListServerNeighbors = 'discovery:ListServerNeighbors',
 StartContinuousExport = 'discovery:StartContinuousExport',
 StartDataCollectionByAgentIds = 'discovery:StartDataCollectionByAgentIds',
 StartExportTask = 'discovery:StartExportTask',
 StartImportTask = 'discovery:StartImportTask',
 StopContinuousExport = 'discovery:StopContinuousExport',
 StopDataCollectionByAgentIds = 'discovery:StopDataCollectionByAgentIds',
 UpdateApplication = 'discovery:UpdateApplication',

}