
export enum ecr {
 BatchCheckLayerAvailability = 'ecr:BatchCheckLayerAvailability',
 BatchDeleteImage = 'ecr:BatchDeleteImage',
 BatchGetImage = 'ecr:BatchGetImage',
 CompleteLayerUpload = 'ecr:CompleteLayerUpload',
 CreateRepository = 'ecr:CreateRepository',
 DeleteLifecyclePolicy = 'ecr:DeleteLifecyclePolicy',
 DeleteRegistryPolicy = 'ecr:DeleteRegistryPolicy',
 DeleteRepository = 'ecr:DeleteRepository',
 DeleteRepositoryPolicy = 'ecr:DeleteRepositoryPolicy',
 DescribeImageScanFindings = 'ecr:DescribeImageScanFindings',
 DescribeImages = 'ecr:DescribeImages',
 DescribeRegistry = 'ecr:DescribeRegistry',
 DescribeRepositories = 'ecr:DescribeRepositories',
 GetAuthorizationToken = 'ecr:GetAuthorizationToken',
 GetDownloadUrlForLayer = 'ecr:GetDownloadUrlForLayer',
 GetLifecyclePolicy = 'ecr:GetLifecyclePolicy',
 GetLifecyclePolicyPreview = 'ecr:GetLifecyclePolicyPreview',
 GetRegistryPolicy = 'ecr:GetRegistryPolicy',
 GetRepositoryPolicy = 'ecr:GetRepositoryPolicy',
 InitiateLayerUpload = 'ecr:InitiateLayerUpload',
 ListImages = 'ecr:ListImages',
 ListTagsForResource = 'ecr:ListTagsForResource',
 PutImage = 'ecr:PutImage',
 PutImageScanningConfiguration = 'ecr:PutImageScanningConfiguration',
 PutImageTagMutability = 'ecr:PutImageTagMutability',
 PutLifecyclePolicy = 'ecr:PutLifecyclePolicy',
 PutRegistryPolicy = 'ecr:PutRegistryPolicy',
 PutReplicationConfiguration = 'ecr:PutReplicationConfiguration',
 ReplicateImage = 'ecr:ReplicateImage',
 SetRepositoryPolicy = 'ecr:SetRepositoryPolicy',
 StartImageScan = 'ecr:StartImageScan',
 StartLifecyclePolicyPreview = 'ecr:StartLifecyclePolicyPreview',
 TagResource = 'ecr:TagResource',
 UntagResource = 'ecr:UntagResource',
 UploadLayerPart = 'ecr:UploadLayerPart',

}