
export enum ecr_public {
 All = 'ecr-public:*',
 Batch = 'ecr-public:Batch*',
 Delete = 'ecr-public:Delete*',
 Describe = 'ecr-public:Describe*',
 Get = 'ecr-public:Get*',
 Put = 'ecr-public:Put*',
 BatchCheckLayerAvailability = 'ecr-public:BatchCheckLayerAvailability',
 BatchDeleteImage = 'ecr-public:BatchDeleteImage',
 CompleteLayerUpload = 'ecr-public:CompleteLayerUpload',
 CreateRepository = 'ecr-public:CreateRepository',
 DeleteRepository = 'ecr-public:DeleteRepository',
 DeleteRepositoryPolicy = 'ecr-public:DeleteRepositoryPolicy',
 DescribeImageTags = 'ecr-public:DescribeImageTags',
 DescribeImages = 'ecr-public:DescribeImages',
 DescribeRegistries = 'ecr-public:DescribeRegistries',
 DescribeRepositories = 'ecr-public:DescribeRepositories',
 GetAuthorizationToken = 'ecr-public:GetAuthorizationToken',
 GetRegistryCatalogData = 'ecr-public:GetRegistryCatalogData',
 GetRepositoryCatalogData = 'ecr-public:GetRepositoryCatalogData',
 GetRepositoryPolicy = 'ecr-public:GetRepositoryPolicy',
 InitiateLayerUpload = 'ecr-public:InitiateLayerUpload',
 PutImage = 'ecr-public:PutImage',
 PutRegistryCatalogData = 'ecr-public:PutRegistryCatalogData',
 PutRepositoryCatalogData = 'ecr-public:PutRepositoryCatalogData',
 SetRepositoryPolicy = 'ecr-public:SetRepositoryPolicy',
 UploadLayerPart = 'ecr-public:UploadLayerPart',

}