
export enum eks {
 AccessKubernetesApi = 'eks:AccessKubernetesApi',
 CreateAddon = 'eks:CreateAddon',
 CreateCluster = 'eks:CreateCluster',
 CreateFargateProfile = 'eks:CreateFargateProfile',
 CreateNodegroup = 'eks:CreateNodegroup',
 DeleteAddon = 'eks:DeleteAddon',
 DeleteCluster = 'eks:DeleteCluster',
 DeleteFargateProfile = 'eks:DeleteFargateProfile',
 DeleteNodegroup = 'eks:DeleteNodegroup',
 DescribeAddon = 'eks:DescribeAddon',
 DescribeAddonVersions = 'eks:DescribeAddonVersions',
 DescribeCluster = 'eks:DescribeCluster',
 DescribeFargateProfile = 'eks:DescribeFargateProfile',
 DescribeNodegroup = 'eks:DescribeNodegroup',
 DescribeUpdate = 'eks:DescribeUpdate',
 ListAddons = 'eks:ListAddons',
 ListClusters = 'eks:ListClusters',
 ListFargateProfiles = 'eks:ListFargateProfiles',
 ListNodegroups = 'eks:ListNodegroups',
 ListTagsForResource = 'eks:ListTagsForResource',
 ListUpdates = 'eks:ListUpdates',
 TagResource = 'eks:TagResource',
 UntagResource = 'eks:UntagResource',
 UpdateAddon = 'eks:UpdateAddon',
 UpdateClusterConfig = 'eks:UpdateClusterConfig',
 UpdateClusterVersion = 'eks:UpdateClusterVersion',
 UpdateNodegroupConfig = 'eks:UpdateNodegroupConfig',
 UpdateNodegroupVersion = 'eks:UpdateNodegroupVersion',

}