
export enum elastictranscoder {
 All = 'elastictranscoder:*',
 Create = 'elastictranscoder:Create*',
 Delete = 'elastictranscoder:Delete*',
 List = 'elastictranscoder:List*',
 Read = 'elastictranscoder:Read*',
 Update = 'elastictranscoder:Update*',
 CancelJob = 'elastictranscoder:CancelJob',
 CreateJob = 'elastictranscoder:CreateJob',
 CreatePipeline = 'elastictranscoder:CreatePipeline',
 CreatePreset = 'elastictranscoder:CreatePreset',
 DeletePipeline = 'elastictranscoder:DeletePipeline',
 DeletePreset = 'elastictranscoder:DeletePreset',
 ListJobsByPipeline = 'elastictranscoder:ListJobsByPipeline',
 ListJobsByStatus = 'elastictranscoder:ListJobsByStatus',
 ListPipelines = 'elastictranscoder:ListPipelines',
 ListPresets = 'elastictranscoder:ListPresets',
 ReadJob = 'elastictranscoder:ReadJob',
 ReadPipeline = 'elastictranscoder:ReadPipeline',
 ReadPreset = 'elastictranscoder:ReadPreset',
 TestRole = 'elastictranscoder:TestRole',
 UpdatePipeline = 'elastictranscoder:UpdatePipeline',
 UpdatePipelineNotifications = 'elastictranscoder:UpdatePipelineNotifications',
 UpdatePipelineStatus = 'elastictranscoder:UpdatePipelineStatus',

}