
export enum elasticfilesystem {
 All = 'elasticfilesystem:*',
 Client = 'elasticfilesystem:Client*',
 Create = 'elasticfilesystem:Create*',
 Delete = 'elasticfilesystem:Delete*',
 Describe = 'elasticfilesystem:Describe*',
 Put = 'elasticfilesystem:Put*',
 Backup = 'elasticfilesystem:Backup',
 ClientMount = 'elasticfilesystem:ClientMount',
 ClientRootAccess = 'elasticfilesystem:ClientRootAccess',
 ClientWrite = 'elasticfilesystem:ClientWrite',
 CreateAccessPoint = 'elasticfilesystem:CreateAccessPoint',
 CreateFileSystem = 'elasticfilesystem:CreateFileSystem',
 CreateMountTarget = 'elasticfilesystem:CreateMountTarget',
 CreateTags = 'elasticfilesystem:CreateTags',
 DeleteAccessPoint = 'elasticfilesystem:DeleteAccessPoint',
 DeleteFileSystem = 'elasticfilesystem:DeleteFileSystem',
 DeleteFileSystemPolicy = 'elasticfilesystem:DeleteFileSystemPolicy',
 DeleteMountTarget = 'elasticfilesystem:DeleteMountTarget',
 DeleteTags = 'elasticfilesystem:DeleteTags',
 DescribeAccessPoints = 'elasticfilesystem:DescribeAccessPoints',
 DescribeBackupPolicy = 'elasticfilesystem:DescribeBackupPolicy',
 DescribeFileSystemPolicy = 'elasticfilesystem:DescribeFileSystemPolicy',
 DescribeFileSystems = 'elasticfilesystem:DescribeFileSystems',
 DescribeLifecycleConfiguration = 'elasticfilesystem:DescribeLifecycleConfiguration',
 DescribeMountTargetSecurityGroups = 'elasticfilesystem:DescribeMountTargetSecurityGroups',
 DescribeMountTargets = 'elasticfilesystem:DescribeMountTargets',
 DescribeTags = 'elasticfilesystem:DescribeTags',
 ListTagsForResource = 'elasticfilesystem:ListTagsForResource',
 ModifyMountTargetSecurityGroups = 'elasticfilesystem:ModifyMountTargetSecurityGroups',
 PutBackupPolicy = 'elasticfilesystem:PutBackupPolicy',
 PutFileSystemPolicy = 'elasticfilesystem:PutFileSystemPolicy',
 PutLifecycleConfiguration = 'elasticfilesystem:PutLifecycleConfiguration',
 Restore = 'elasticfilesystem:Restore',
 TagResource = 'elasticfilesystem:TagResource',
 UntagResource = 'elasticfilesystem:UntagResource',
 UpdateFileSystem = 'elasticfilesystem:UpdateFileSystem',

}