
export enum es {
 All = 'es:*',
 Create = 'es:Create*',
 Delete = 'es:Delete*',
 Describe = 'es:Describe*',
 E = 'es:E*',
 Get = 'es:Get*',
 List = 'es:List*',
 AcceptInboundCrossClusterSearchConnection = 'es:AcceptInboundCrossClusterSearchConnection',
 AddTags = 'es:AddTags',
 CreateElasticsearchDomain = 'es:CreateElasticsearchDomain',
 CreateElasticsearchServiceRole = 'es:CreateElasticsearchServiceRole',
 CreateOutboundCrossClusterSearchConnection = 'es:CreateOutboundCrossClusterSearchConnection',
 DeleteElasticsearchDomain = 'es:DeleteElasticsearchDomain',
 DeleteElasticsearchServiceRole = 'es:DeleteElasticsearchServiceRole',
 DeleteInboundCrossClusterSearchConnection = 'es:DeleteInboundCrossClusterSearchConnection',
 DeleteOutboundCrossClusterSearchConnection = 'es:DeleteOutboundCrossClusterSearchConnection',
 DescribeElasticsearchDomain = 'es:DescribeElasticsearchDomain',
 DescribeElasticsearchDomainConfig = 'es:DescribeElasticsearchDomainConfig',
 DescribeElasticsearchDomains = 'es:DescribeElasticsearchDomains',
 DescribeElasticsearchInstanceTypeLimits = 'es:DescribeElasticsearchInstanceTypeLimits',
 DescribeInboundCrossClusterSearchConnections = 'es:DescribeInboundCrossClusterSearchConnections',
 DescribeOutboundCrossClusterSearchConnections = 'es:DescribeOutboundCrossClusterSearchConnections',
 DescribeReservedElasticsearchInstanceOfferings = 'es:DescribeReservedElasticsearchInstanceOfferings',
 DescribeReservedElasticsearchInstances = 'es:DescribeReservedElasticsearchInstances',
 ESCrossClusterGet = 'es:ESCrossClusterGet',
 ESHttpDelete = 'es:ESHttpDelete',
 ESHttpGet = 'es:ESHttpGet',
 ESHttpHead = 'es:ESHttpHead',
 ESHttpPatch = 'es:ESHttpPatch',
 ESHttpPost = 'es:ESHttpPost',
 ESHttpPut = 'es:ESHttpPut',
 GetCompatibleElasticsearchVersions = 'es:GetCompatibleElasticsearchVersions',
 GetUpgradeHistory = 'es:GetUpgradeHistory',
 GetUpgradeStatus = 'es:GetUpgradeStatus',
 ListDomainNames = 'es:ListDomainNames',
 ListElasticsearchInstanceTypeDetails = 'es:ListElasticsearchInstanceTypeDetails',
 ListElasticsearchInstanceTypes = 'es:ListElasticsearchInstanceTypes',
 ListElasticsearchVersions = 'es:ListElasticsearchVersions',
 ListTags = 'es:ListTags',
 PurchaseReservedElasticsearchInstanceOffering = 'es:PurchaseReservedElasticsearchInstanceOffering',
 RejectInboundCrossClusterSearchConnection = 'es:RejectInboundCrossClusterSearchConnection',
 RemoveTags = 'es:RemoveTags',
 UpdateElasticsearchDomainConfig = 'es:UpdateElasticsearchDomainConfig',
 UpgradeElasticsearchDomain = 'es:UpgradeElasticsearchDomain',

}