
export enum events {
 ActivateEventSource = 'events:ActivateEventSource',
 CancelReplay = 'events:CancelReplay',
 CreateArchive = 'events:CreateArchive',
 CreateEventBus = 'events:CreateEventBus',
 CreatePartnerEventSource = 'events:CreatePartnerEventSource',
 DeactivateEventSource = 'events:DeactivateEventSource',
 DeleteArchive = 'events:DeleteArchive',
 DeleteEventBus = 'events:DeleteEventBus',
 DeletePartnerEventSource = 'events:DeletePartnerEventSource',
 DeleteRule = 'events:DeleteRule',
 DescribeArchive = 'events:DescribeArchive',
 DescribeEventBus = 'events:DescribeEventBus',
 DescribeEventSource = 'events:DescribeEventSource',
 DescribePartnerEventSource = 'events:DescribePartnerEventSource',
 DescribeReplay = 'events:DescribeReplay',
 DescribeRule = 'events:DescribeRule',
 DisableRule = 'events:DisableRule',
 EnableRule = 'events:EnableRule',
 ListArchives = 'events:ListArchives',
 ListEventBuses = 'events:ListEventBuses',
 ListEventSources = 'events:ListEventSources',
 ListPartnerEventSourceAccounts = 'events:ListPartnerEventSourceAccounts',
 ListPartnerEventSources = 'events:ListPartnerEventSources',
 ListReplays = 'events:ListReplays',
 ListRuleNamesByTarget = 'events:ListRuleNamesByTarget',
 ListRules = 'events:ListRules',
 ListTagsForResource = 'events:ListTagsForResource',
 ListTargetsByRule = 'events:ListTargetsByRule',
 PutEvents = 'events:PutEvents',
 PutPartnerEvents = 'events:PutPartnerEvents',
 PutPermission = 'events:PutPermission',
 PutRule = 'events:PutRule',
 PutTargets = 'events:PutTargets',
 RemovePermission = 'events:RemovePermission',
 RemoveTargets = 'events:RemoveTargets',
 StartReplay = 'events:StartReplay',
 TagResource = 'events:TagResource',
 TestEventPattern = 'events:TestEventPattern',
 UntagResource = 'events:UntagResource',
 UpdateArchive = 'events:UpdateArchive',

}