
export enum fms {
 AssociateAdminAccount = 'fms:AssociateAdminAccount',
 DeleteAppsList = 'fms:DeleteAppsList',
 DeleteNotificationChannel = 'fms:DeleteNotificationChannel',
 DeletePolicy = 'fms:DeletePolicy',
 DeleteProtocolsList = 'fms:DeleteProtocolsList',
 DisassociateAdminAccount = 'fms:DisassociateAdminAccount',
 GetAdminAccount = 'fms:GetAdminAccount',
 GetAppsList = 'fms:GetAppsList',
 GetComplianceDetail = 'fms:GetComplianceDetail',
 GetNotificationChannel = 'fms:GetNotificationChannel',
 GetPolicy = 'fms:GetPolicy',
 GetProtectionStatus = 'fms:GetProtectionStatus',
 GetProtocolsList = 'fms:GetProtocolsList',
 GetViolationDetails = 'fms:GetViolationDetails',
 ListAppsLists = 'fms:ListAppsLists',
 ListComplianceStatus = 'fms:ListComplianceStatus',
 ListMemberAccounts = 'fms:ListMemberAccounts',
 ListPolicies = 'fms:ListPolicies',
 ListProtocolsLists = 'fms:ListProtocolsLists',
 ListTagsForResource = 'fms:ListTagsForResource',
 PutAppsList = 'fms:PutAppsList',
 PutNotificationChannel = 'fms:PutNotificationChannel',
 PutPolicy = 'fms:PutPolicy',
 PutProtocolsList = 'fms:PutProtocolsList',
 TagResource = 'fms:TagResource',
 UntagResource = 'fms:UntagResource',

}