
export enum forecast {
 CreateDataset = 'forecast:CreateDataset',
 CreateDatasetGroup = 'forecast:CreateDatasetGroup',
 CreateDatasetImportJob = 'forecast:CreateDatasetImportJob',
 CreateForecast = 'forecast:CreateForecast',
 CreateForecastExportJob = 'forecast:CreateForecastExportJob',
 CreatePredictor = 'forecast:CreatePredictor',
 CreatePredictorBacktestExportJob = 'forecast:CreatePredictorBacktestExportJob',
 DeleteDataset = 'forecast:DeleteDataset',
 DeleteDatasetGroup = 'forecast:DeleteDatasetGroup',
 DeleteDatasetImportJob = 'forecast:DeleteDatasetImportJob',
 DeleteForecast = 'forecast:DeleteForecast',
 DeleteForecastExportJob = 'forecast:DeleteForecastExportJob',
 DeletePredictor = 'forecast:DeletePredictor',
 DeletePredictorBacktestExportJob = 'forecast:DeletePredictorBacktestExportJob',
 DescribeDataset = 'forecast:DescribeDataset',
 DescribeDatasetGroup = 'forecast:DescribeDatasetGroup',
 DescribeDatasetImportJob = 'forecast:DescribeDatasetImportJob',
 DescribeForecast = 'forecast:DescribeForecast',
 DescribeForecastExportJob = 'forecast:DescribeForecastExportJob',
 DescribePredictor = 'forecast:DescribePredictor',
 DescribePredictorBacktestExportJob = 'forecast:DescribePredictorBacktestExportJob',
 GetAccuracyMetrics = 'forecast:GetAccuracyMetrics',
 ListDatasetGroups = 'forecast:ListDatasetGroups',
 ListDatasetImportJobs = 'forecast:ListDatasetImportJobs',
 ListDatasets = 'forecast:ListDatasets',
 ListForecastExportJobs = 'forecast:ListForecastExportJobs',
 ListForecasts = 'forecast:ListForecasts',
 ListPredictorBacktestExportJobs = 'forecast:ListPredictorBacktestExportJobs',
 ListPredictors = 'forecast:ListPredictors',
 ListTagsForResource = 'forecast:ListTagsForResource',
 QueryForecast = 'forecast:QueryForecast',
 TagResource = 'forecast:TagResource',
 UntagResource = 'forecast:UntagResource',
 UpdateDatasetGroup = 'forecast:UpdateDatasetGroup',

}