
export enum geo {
 AssociateTrackerConsumer = 'geo:AssociateTrackerConsumer',
 BatchDeleteGeofence = 'geo:BatchDeleteGeofence',
 BatchEvaluateGeofences = 'geo:BatchEvaluateGeofences',
 BatchGetDevicePosition = 'geo:BatchGetDevicePosition',
 BatchPutGeofence = 'geo:BatchPutGeofence',
 BatchUpdateDevicePosition = 'geo:BatchUpdateDevicePosition',
 CreateGeofenceCollection = 'geo:CreateGeofenceCollection',
 CreateMap = 'geo:CreateMap',
 CreatePlaceIndex = 'geo:CreatePlaceIndex',
 CreateTracker = 'geo:CreateTracker',
 DeleteGeofenceCollection = 'geo:DeleteGeofenceCollection',
 DeleteMap = 'geo:DeleteMap',
 DeletePlaceIndex = 'geo:DeletePlaceIndex',
 DeleteTracker = 'geo:DeleteTracker',
 DescribeGeofenceCollection = 'geo:DescribeGeofenceCollection',
 DescribeMap = 'geo:DescribeMap',
 DescribePlaceIndex = 'geo:DescribePlaceIndex',
 DescribeTracker = 'geo:DescribeTracker',
 DisassociateTrackerConsumer = 'geo:DisassociateTrackerConsumer',
 GetDevicePosition = 'geo:GetDevicePosition',
 GetDevicePositionHistory = 'geo:GetDevicePositionHistory',
 GetGeofence = 'geo:GetGeofence',
 GetMapGlyphs = 'geo:GetMapGlyphs',
 GetMapSprites = 'geo:GetMapSprites',
 GetMapStyleDescriptor = 'geo:GetMapStyleDescriptor',
 GetMapTile = 'geo:GetMapTile',
 GetMapTileJson = 'geo:GetMapTileJson',
 ListGeofenceCollections = 'geo:ListGeofenceCollections',
 ListGeofences = 'geo:ListGeofences',
 ListMaps = 'geo:ListMaps',
 ListPlaceIndexes = 'geo:ListPlaceIndexes',
 ListTrackerConsumers = 'geo:ListTrackerConsumers',
 ListTrackers = 'geo:ListTrackers',
 PutGeofence = 'geo:PutGeofence',
 SearchPlaceIndexForPosition = 'geo:SearchPlaceIndexForPosition',
 SearchPlaceIndexForText = 'geo:SearchPlaceIndexForText',
 UpdateGeofenceCollection = 'geo:UpdateGeofenceCollection',
 UpdateTracker = 'geo:UpdateTracker',

}