
export enum glacier {
 All = 'glacier:*',
 Abort = 'glacier:Abort*',
 Complete = 'glacier:Complete*',
 Delete = 'glacier:Delete*',
 Describe = 'glacier:Describe*',
 Get = 'glacier:Get*',
 Initiate = 'glacier:Initiate*',
 List = 'glacier:List*',
 Set = 'glacier:Set*',
 Upload = 'glacier:Upload*',
 AbortMultipartUpload = 'glacier:AbortMultipartUpload',
 AbortVaultLock = 'glacier:AbortVaultLock',
 AddTagsToVault = 'glacier:AddTagsToVault',
 CompleteMultipartUpload = 'glacier:CompleteMultipartUpload',
 CompleteVaultLock = 'glacier:CompleteVaultLock',
 CreateVault = 'glacier:CreateVault',
 DeleteArchive = 'glacier:DeleteArchive',
 DeleteVault = 'glacier:DeleteVault',
 DeleteVaultAccessPolicy = 'glacier:DeleteVaultAccessPolicy',
 DeleteVaultNotifications = 'glacier:DeleteVaultNotifications',
 DescribeJob = 'glacier:DescribeJob',
 DescribeVault = 'glacier:DescribeVault',
 GetDataRetrievalPolicy = 'glacier:GetDataRetrievalPolicy',
 GetJobOutput = 'glacier:GetJobOutput',
 GetVaultAccessPolicy = 'glacier:GetVaultAccessPolicy',
 GetVaultLock = 'glacier:GetVaultLock',
 GetVaultNotifications = 'glacier:GetVaultNotifications',
 InitiateJob = 'glacier:InitiateJob',
 InitiateMultipartUpload = 'glacier:InitiateMultipartUpload',
 InitiateVaultLock = 'glacier:InitiateVaultLock',
 ListJobs = 'glacier:ListJobs',
 ListMultipartUploads = 'glacier:ListMultipartUploads',
 ListParts = 'glacier:ListParts',
 ListProvisionedCapacity = 'glacier:ListProvisionedCapacity',
 ListTagsForVault = 'glacier:ListTagsForVault',
 ListVaults = 'glacier:ListVaults',
 PurchaseProvisionedCapacity = 'glacier:PurchaseProvisionedCapacity',
 RemoveTagsFromVault = 'glacier:RemoveTagsFromVault',
 SetDataRetrievalPolicy = 'glacier:SetDataRetrievalPolicy',
 SetVaultAccessPolicy = 'glacier:SetVaultAccessPolicy',
 SetVaultNotifications = 'glacier:SetVaultNotifications',
 UploadArchive = 'glacier:UploadArchive',
 UploadMultipartPart = 'glacier:UploadMultipartPart',

}