
export enum groundstation {
 CancelContact = 'groundstation:CancelContact',
 CreateConfig = 'groundstation:CreateConfig',
 CreateDataflowEndpointGroup = 'groundstation:CreateDataflowEndpointGroup',
 CreateMissionProfile = 'groundstation:CreateMissionProfile',
 DeleteConfig = 'groundstation:DeleteConfig',
 DeleteDataflowEndpointGroup = 'groundstation:DeleteDataflowEndpointGroup',
 DeleteMissionProfile = 'groundstation:DeleteMissionProfile',
 DescribeContact = 'groundstation:DescribeContact',
 GetConfig = 'groundstation:GetConfig',
 GetDataflowEndpointGroup = 'groundstation:GetDataflowEndpointGroup',
 GetMinuteUsage = 'groundstation:GetMinuteUsage',
 GetMissionProfile = 'groundstation:GetMissionProfile',
 GetSatellite = 'groundstation:GetSatellite',
 ListConfigs = 'groundstation:ListConfigs',
 ListContacts = 'groundstation:ListContacts',
 ListDataflowEndpointGroups = 'groundstation:ListDataflowEndpointGroups',
 ListGroundStations = 'groundstation:ListGroundStations',
 ListMissionProfiles = 'groundstation:ListMissionProfiles',
 ListSatellites = 'groundstation:ListSatellites',
 ListTagsForResource = 'groundstation:ListTagsForResource',
 ReserveContact = 'groundstation:ReserveContact',
 TagResource = 'groundstation:TagResource',
 UntagResource = 'groundstation:UntagResource',
 UpdateConfig = 'groundstation:UpdateConfig',
 UpdateMissionProfile = 'groundstation:UpdateMissionProfile',

}