
export enum inspector {
 All = 'inspector:*',
 Create = 'inspector:Create*',
 Delete = 'inspector:Delete*',
 Describe = 'inspector:Describe*',
 List = 'inspector:List*',
 AddAttributesToFindings = 'inspector:AddAttributesToFindings',
 CreateAssessmentTarget = 'inspector:CreateAssessmentTarget',
 CreateAssessmentTemplate = 'inspector:CreateAssessmentTemplate',
 CreateResourceGroup = 'inspector:CreateResourceGroup',
 DeleteAssessmentRun = 'inspector:DeleteAssessmentRun',
 DeleteAssessmentTarget = 'inspector:DeleteAssessmentTarget',
 DeleteAssessmentTemplate = 'inspector:DeleteAssessmentTemplate',
 DescribeAssessmentRuns = 'inspector:DescribeAssessmentRuns',
 DescribeAssessmentTargets = 'inspector:DescribeAssessmentTargets',
 DescribeAssessmentTemplates = 'inspector:DescribeAssessmentTemplates',
 DescribeCrossAccountAccessRole = 'inspector:DescribeCrossAccountAccessRole',
 DescribeFindings = 'inspector:DescribeFindings',
 DescribeResourceGroups = 'inspector:DescribeResourceGroups',
 DescribeRulesPackages = 'inspector:DescribeRulesPackages',
 GetTelemetryMetadata = 'inspector:GetTelemetryMetadata',
 ListAssessmentRunAgents = 'inspector:ListAssessmentRunAgents',
 ListAssessmentRuns = 'inspector:ListAssessmentRuns',
 ListAssessmentTargets = 'inspector:ListAssessmentTargets',
 ListAssessmentTemplates = 'inspector:ListAssessmentTemplates',
 ListEventSubscriptions = 'inspector:ListEventSubscriptions',
 ListFindings = 'inspector:ListFindings',
 ListRulesPackages = 'inspector:ListRulesPackages',
 ListTagsForResource = 'inspector:ListTagsForResource',
 PreviewAgents = 'inspector:PreviewAgents',
 RegisterCrossAccountAccessRole = 'inspector:RegisterCrossAccountAccessRole',
 RemoveAttributesFromFindings = 'inspector:RemoveAttributesFromFindings',
 SetTagsForResource = 'inspector:SetTagsForResource',
 StartAssessmentRun = 'inspector:StartAssessmentRun',
 StopAssessmentRun = 'inspector:StopAssessmentRun',
 SubscribeToEvent = 'inspector:SubscribeToEvent',
 UnsubscribeFromEvent = 'inspector:UnsubscribeFromEvent',
 UpdateAssessmentTarget = 'inspector:UpdateAssessmentTarget',

}