
export enum iot1click {
 All = 'iot1click:*',
 Create = 'iot1click:Create*',
 Delete = 'iot1click:Delete*',
 Describe = 'iot1click:Describe*',
 Get = 'iot1click:Get*',
 List = 'iot1click:List*',
 Update = 'iot1click:Update*',
 AssociateDeviceWithPlacement = 'iot1click:AssociateDeviceWithPlacement',
 ClaimDevicesByClaimCode = 'iot1click:ClaimDevicesByClaimCode',
 CreatePlacement = 'iot1click:CreatePlacement',
 CreateProject = 'iot1click:CreateProject',
 DeletePlacement = 'iot1click:DeletePlacement',
 DeleteProject = 'iot1click:DeleteProject',
 DescribeDevice = 'iot1click:DescribeDevice',
 DescribePlacement = 'iot1click:DescribePlacement',
 DescribeProject = 'iot1click:DescribeProject',
 DisassociateDeviceFromPlacement = 'iot1click:DisassociateDeviceFromPlacement',
 FinalizeDeviceClaim = 'iot1click:FinalizeDeviceClaim',
 GetDeviceMethods = 'iot1click:GetDeviceMethods',
 GetDevicesInPlacement = 'iot1click:GetDevicesInPlacement',
 InitiateDeviceClaim = 'iot1click:InitiateDeviceClaim',
 InvokeDeviceMethod = 'iot1click:InvokeDeviceMethod',
 ListDeviceEvents = 'iot1click:ListDeviceEvents',
 ListDevices = 'iot1click:ListDevices',
 ListPlacements = 'iot1click:ListPlacements',
 ListProjects = 'iot1click:ListProjects',
 ListTagsForResource = 'iot1click:ListTagsForResource',
 TagResource = 'iot1click:TagResource',
 UnclaimDevice = 'iot1click:UnclaimDevice',
 UntagResource = 'iot1click:UntagResource',
 UpdateDeviceState = 'iot1click:UpdateDeviceState',
 UpdatePlacement = 'iot1click:UpdatePlacement',
 UpdateProject = 'iot1click:UpdateProject',

}