
export enum iotanalytics {
 BatchPutMessage = 'iotanalytics:BatchPutMessage',
 CancelPipelineReprocessing = 'iotanalytics:CancelPipelineReprocessing',
 CreateChannel = 'iotanalytics:CreateChannel',
 CreateDataset = 'iotanalytics:CreateDataset',
 CreateDatasetContent = 'iotanalytics:CreateDatasetContent',
 CreateDatastore = 'iotanalytics:CreateDatastore',
 CreatePipeline = 'iotanalytics:CreatePipeline',
 DeleteChannel = 'iotanalytics:DeleteChannel',
 DeleteDataset = 'iotanalytics:DeleteDataset',
 DeleteDatasetContent = 'iotanalytics:DeleteDatasetContent',
 DeleteDatastore = 'iotanalytics:DeleteDatastore',
 DeletePipeline = 'iotanalytics:DeletePipeline',
 DescribeChannel = 'iotanalytics:DescribeChannel',
 DescribeDataset = 'iotanalytics:DescribeDataset',
 DescribeDatastore = 'iotanalytics:DescribeDatastore',
 DescribeLoggingOptions = 'iotanalytics:DescribeLoggingOptions',
 DescribePipeline = 'iotanalytics:DescribePipeline',
 GetDatasetContent = 'iotanalytics:GetDatasetContent',
 ListChannels = 'iotanalytics:ListChannels',
 ListDatasets = 'iotanalytics:ListDatasets',
 ListDatastores = 'iotanalytics:ListDatastores',
 ListPipelines = 'iotanalytics:ListPipelines',
 ListTagsForResource = 'iotanalytics:ListTagsForResource',
 PutLoggingOptions = 'iotanalytics:PutLoggingOptions',
 RunPipelineActivity = 'iotanalytics:RunPipelineActivity',
 SampleChannelData = 'iotanalytics:SampleChannelData',
 StartPipelineReprocessing = 'iotanalytics:StartPipelineReprocessing',
 TagResource = 'iotanalytics:TagResource',
 UntagResource = 'iotanalytics:UntagResource',
 UpdateChannel = 'iotanalytics:UpdateChannel',
 UpdateDataset = 'iotanalytics:UpdateDataset',
 UpdateDatastore = 'iotanalytics:UpdateDatastore',
 UpdatePipeline = 'iotanalytics:UpdatePipeline',

}