
export enum iotevents {
 BatchAcknowledgeAlarm = 'iotevents:BatchAcknowledgeAlarm',
 BatchDisableAlarm = 'iotevents:BatchDisableAlarm',
 BatchEnableAlarm = 'iotevents:BatchEnableAlarm',
 BatchPutMessage = 'iotevents:BatchPutMessage',
 BatchResetAlarm = 'iotevents:BatchResetAlarm',
 BatchSnoozeAlarm = 'iotevents:BatchSnoozeAlarm',
 BatchUpdateDetector = 'iotevents:BatchUpdateDetector',
 CreateAlarmModel = 'iotevents:CreateAlarmModel',
 CreateDetectorModel = 'iotevents:CreateDetectorModel',
 CreateInput = 'iotevents:CreateInput',
 DeleteAlarmModel = 'iotevents:DeleteAlarmModel',
 DeleteDetectorModel = 'iotevents:DeleteDetectorModel',
 DeleteInput = 'iotevents:DeleteInput',
 DescribeAlarm = 'iotevents:DescribeAlarm',
 DescribeAlarmModel = 'iotevents:DescribeAlarmModel',
 DescribeDetector = 'iotevents:DescribeDetector',
 DescribeDetectorModel = 'iotevents:DescribeDetectorModel',
 DescribeInput = 'iotevents:DescribeInput',
 DescribeLoggingOptions = 'iotevents:DescribeLoggingOptions',
 ListAlarmModelVersions = 'iotevents:ListAlarmModelVersions',
 ListAlarmModels = 'iotevents:ListAlarmModels',
 ListAlarms = 'iotevents:ListAlarms',
 ListDetectorModelVersions = 'iotevents:ListDetectorModelVersions',
 ListDetectorModels = 'iotevents:ListDetectorModels',
 ListDetectors = 'iotevents:ListDetectors',
 ListInputs = 'iotevents:ListInputs',
 ListTagsForResource = 'iotevents:ListTagsForResource',
 PutLoggingOptions = 'iotevents:PutLoggingOptions',
 TagResource = 'iotevents:TagResource',
 UntagResource = 'iotevents:UntagResource',
 UpdateAlarmModel = 'iotevents:UpdateAlarmModel',
 UpdateDetectorModel = 'iotevents:UpdateDetectorModel',
 UpdateInput = 'iotevents:UpdateInput',
 UpdateInputRouting = 'iotevents:UpdateInputRouting',

}