
export enum iotthingsgraph {
 All = 'iotthingsgraph:*',
 Create = 'iotthingsgraph:Create*',
 Delete = 'iotthingsgraph:Delete*',
 Deprecate = 'iotthingsgraph:Deprecate*',
 Get = 'iotthingsgraph:Get*',
 List = 'iotthingsgraph:List*',
 Search = 'iotthingsgraph:Search*',
 Update = 'iotthingsgraph:Update*',
 AssociateEntityToThing = 'iotthingsgraph:AssociateEntityToThing',
 CreateFlowTemplate = 'iotthingsgraph:CreateFlowTemplate',
 CreateSystemInstance = 'iotthingsgraph:CreateSystemInstance',
 CreateSystemTemplate = 'iotthingsgraph:CreateSystemTemplate',
 DeleteFlowTemplate = 'iotthingsgraph:DeleteFlowTemplate',
 DeleteNamespace = 'iotthingsgraph:DeleteNamespace',
 DeleteSystemInstance = 'iotthingsgraph:DeleteSystemInstance',
 DeleteSystemTemplate = 'iotthingsgraph:DeleteSystemTemplate',
 DeploySystemInstance = 'iotthingsgraph:DeploySystemInstance',
 DeprecateFlowTemplate = 'iotthingsgraph:DeprecateFlowTemplate',
 DeprecateSystemTemplate = 'iotthingsgraph:DeprecateSystemTemplate',
 DescribeNamespace = 'iotthingsgraph:DescribeNamespace',
 DissociateEntityFromThing = 'iotthingsgraph:DissociateEntityFromThing',
 GetEntities = 'iotthingsgraph:GetEntities',
 GetFlowTemplate = 'iotthingsgraph:GetFlowTemplate',
 GetFlowTemplateRevisions = 'iotthingsgraph:GetFlowTemplateRevisions',
 GetNamespaceDeletionStatus = 'iotthingsgraph:GetNamespaceDeletionStatus',
 GetSystemInstance = 'iotthingsgraph:GetSystemInstance',
 GetSystemTemplate = 'iotthingsgraph:GetSystemTemplate',
 GetSystemTemplateRevisions = 'iotthingsgraph:GetSystemTemplateRevisions',
 GetUploadStatus = 'iotthingsgraph:GetUploadStatus',
 ListFlowExecutionMessages = 'iotthingsgraph:ListFlowExecutionMessages',
 ListTagsForResource = 'iotthingsgraph:ListTagsForResource',
 SearchEntities = 'iotthingsgraph:SearchEntities',
 SearchFlowExecutions = 'iotthingsgraph:SearchFlowExecutions',
 SearchFlowTemplates = 'iotthingsgraph:SearchFlowTemplates',
 SearchSystemInstances = 'iotthingsgraph:SearchSystemInstances',
 SearchSystemTemplates = 'iotthingsgraph:SearchSystemTemplates',
 SearchThings = 'iotthingsgraph:SearchThings',
 TagResource = 'iotthingsgraph:TagResource',
 UndeploySystemInstance = 'iotthingsgraph:UndeploySystemInstance',
 UntagResource = 'iotthingsgraph:UntagResource',
 UpdateFlowTemplate = 'iotthingsgraph:UpdateFlowTemplate',
 UpdateSystemTemplate = 'iotthingsgraph:UpdateSystemTemplate',
 UploadEntityDefinitions = 'iotthingsgraph:UploadEntityDefinitions',

}