
export enum kafka {
 BatchAssociateScramSecret = 'kafka:BatchAssociateScramSecret',
 BatchDisassociateScramSecret = 'kafka:BatchDisassociateScramSecret',
 CreateCluster = 'kafka:CreateCluster',
 CreateConfiguration = 'kafka:CreateConfiguration',
 DeleteCluster = 'kafka:DeleteCluster',
 DeleteConfiguration = 'kafka:DeleteConfiguration',
 DescribeCluster = 'kafka:DescribeCluster',
 DescribeClusterOperation = 'kafka:DescribeClusterOperation',
 DescribeConfiguration = 'kafka:DescribeConfiguration',
 DescribeConfigurationRevision = 'kafka:DescribeConfigurationRevision',
 GetBootstrapBrokers = 'kafka:GetBootstrapBrokers',
 GetCompatibleKafkaVersions = 'kafka:GetCompatibleKafkaVersions',
 ListClusterOperations = 'kafka:ListClusterOperations',
 ListClusters = 'kafka:ListClusters',
 ListConfigurationRevisions = 'kafka:ListConfigurationRevisions',
 ListConfigurations = 'kafka:ListConfigurations',
 ListKafkaVersions = 'kafka:ListKafkaVersions',
 ListNodes = 'kafka:ListNodes',
 ListScramSecrets = 'kafka:ListScramSecrets',
 ListTagsForResource = 'kafka:ListTagsForResource',
 RebootBroker = 'kafka:RebootBroker',
 TagResource = 'kafka:TagResource',
 UntagResource = 'kafka:UntagResource',
 UpdateBrokerCount = 'kafka:UpdateBrokerCount',
 UpdateBrokerStorage = 'kafka:UpdateBrokerStorage',
 UpdateBrokerType = 'kafka:UpdateBrokerType',
 UpdateClusterConfiguration = 'kafka:UpdateClusterConfiguration',
 UpdateClusterKafkaVersion = 'kafka:UpdateClusterKafkaVersion',
 UpdateConfiguration = 'kafka:UpdateConfiguration',
 UpdateMonitoring = 'kafka:UpdateMonitoring',

}