
export enum kendra {
 BatchDeleteDocument = 'kendra:BatchDeleteDocument',
 BatchPutDocument = 'kendra:BatchPutDocument',
 CreateDataSource = 'kendra:CreateDataSource',
 CreateFaq = 'kendra:CreateFaq',
 CreateIndex = 'kendra:CreateIndex',
 CreateThesaurus = 'kendra:CreateThesaurus',
 DeleteDataSource = 'kendra:DeleteDataSource',
 DeleteFaq = 'kendra:DeleteFaq',
 DeleteIndex = 'kendra:DeleteIndex',
 DeleteThesaurus = 'kendra:DeleteThesaurus',
 DescribeDataSource = 'kendra:DescribeDataSource',
 DescribeFaq = 'kendra:DescribeFaq',
 DescribeIndex = 'kendra:DescribeIndex',
 DescribeThesaurus = 'kendra:DescribeThesaurus',
 ListDataSourceSyncJobs = 'kendra:ListDataSourceSyncJobs',
 ListDataSources = 'kendra:ListDataSources',
 ListFaqs = 'kendra:ListFaqs',
 ListIndices = 'kendra:ListIndices',
 ListTagsForResource = 'kendra:ListTagsForResource',
 ListThesauri = 'kendra:ListThesauri',
 Query = 'kendra:Query',
 StartDataSourceSyncJob = 'kendra:StartDataSourceSyncJob',
 StopDataSourceSyncJob = 'kendra:StopDataSourceSyncJob',
 SubmitFeedback = 'kendra:SubmitFeedback',
 TagResource = 'kendra:TagResource',
 UntagResource = 'kendra:UntagResource',
 UpdateDataSource = 'kendra:UpdateDataSource',
 UpdateIndex = 'kendra:UpdateIndex',
 UpdateThesaurus = 'kendra:UpdateThesaurus',

}