
export enum kinesisanalytics {
 AddApplicationCloudWatchLoggingOption = 'kinesisanalytics:AddApplicationCloudWatchLoggingOption',
 AddApplicationInput = 'kinesisanalytics:AddApplicationInput',
 AddApplicationInputProcessingConfiguration = 'kinesisanalytics:AddApplicationInputProcessingConfiguration',
 AddApplicationOutput = 'kinesisanalytics:AddApplicationOutput',
 AddApplicationReferenceDataSource = 'kinesisanalytics:AddApplicationReferenceDataSource',
 AddApplicationVpcConfiguration = 'kinesisanalytics:AddApplicationVpcConfiguration',
 CreateApplication = 'kinesisanalytics:CreateApplication',
 CreateApplicationPresignedUrl = 'kinesisanalytics:CreateApplicationPresignedUrl',
 CreateApplicationSnapshot = 'kinesisanalytics:CreateApplicationSnapshot',
 DeleteApplication = 'kinesisanalytics:DeleteApplication',
 DeleteApplicationCloudWatchLoggingOption = 'kinesisanalytics:DeleteApplicationCloudWatchLoggingOption',
 DeleteApplicationInputProcessingConfiguration = 'kinesisanalytics:DeleteApplicationInputProcessingConfiguration',
 DeleteApplicationOutput = 'kinesisanalytics:DeleteApplicationOutput',
 DeleteApplicationReferenceDataSource = 'kinesisanalytics:DeleteApplicationReferenceDataSource',
 DeleteApplicationSnapshot = 'kinesisanalytics:DeleteApplicationSnapshot',
 DeleteApplicationVpcConfiguration = 'kinesisanalytics:DeleteApplicationVpcConfiguration',
 DescribeApplication = 'kinesisanalytics:DescribeApplication',
 DescribeApplicationSnapshot = 'kinesisanalytics:DescribeApplicationSnapshot',
 DiscoverInputSchema = 'kinesisanalytics:DiscoverInputSchema',
 ListApplicationSnapshots = 'kinesisanalytics:ListApplicationSnapshots',
 ListApplications = 'kinesisanalytics:ListApplications',
 ListTagsForResource = 'kinesisanalytics:ListTagsForResource',
 StartApplication = 'kinesisanalytics:StartApplication',
 StopApplication = 'kinesisanalytics:StopApplication',
 TagResource = 'kinesisanalytics:TagResource',
 UntagResource = 'kinesisanalytics:UntagResource',
 UpdateApplication = 'kinesisanalytics:UpdateApplication',
 GetApplicationState = 'kinesisanalytics:GetApplicationState',

}