
export enum kinesis {
 AddTagsToStream = 'kinesis:AddTagsToStream',
 CreateStream = 'kinesis:CreateStream',
 DecreaseStreamRetentionPeriod = 'kinesis:DecreaseStreamRetentionPeriod',
 DeleteStream = 'kinesis:DeleteStream',
 DeregisterStreamConsumer = 'kinesis:DeregisterStreamConsumer',
 DescribeLimits = 'kinesis:DescribeLimits',
 DescribeStream = 'kinesis:DescribeStream',
 DescribeStreamConsumer = 'kinesis:DescribeStreamConsumer',
 DescribeStreamSummary = 'kinesis:DescribeStreamSummary',
 DisableEnhancedMonitoring = 'kinesis:DisableEnhancedMonitoring',
 EnableEnhancedMonitoring = 'kinesis:EnableEnhancedMonitoring',
 GetRecords = 'kinesis:GetRecords',
 GetShardIterator = 'kinesis:GetShardIterator',
 IncreaseStreamRetentionPeriod = 'kinesis:IncreaseStreamRetentionPeriod',
 ListShards = 'kinesis:ListShards',
 ListStreamConsumers = 'kinesis:ListStreamConsumers',
 ListStreams = 'kinesis:ListStreams',
 ListTagsForStream = 'kinesis:ListTagsForStream',
 MergeShards = 'kinesis:MergeShards',
 PutRecord = 'kinesis:PutRecord',
 PutRecords = 'kinesis:PutRecords',
 RegisterStreamConsumer = 'kinesis:RegisterStreamConsumer',
 RemoveTagsFromStream = 'kinesis:RemoveTagsFromStream',
 SplitShard = 'kinesis:SplitShard',
 StartStreamEncryption = 'kinesis:StartStreamEncryption',
 StopStreamEncryption = 'kinesis:StopStreamEncryption',
 SubscribeToShard = 'kinesis:SubscribeToShard',
 UpdateShardCount = 'kinesis:UpdateShardCount',

}