
export enum kinesisvideo {
 All = 'kinesisvideo:*',
 Connect = 'kinesisvideo:Connect*',
 Create = 'kinesisvideo:Create*',
 Delete = 'kinesisvideo:Delete*',
 Describe = 'kinesisvideo:Describe*',
 Get = 'kinesisvideo:Get*',
 List = 'kinesisvideo:List*',
 Tag = 'kinesisvideo:Tag*',
 Untag = 'kinesisvideo:Untag*',
 Update = 'kinesisvideo:Update*',
 ConnectAsMaster = 'kinesisvideo:ConnectAsMaster',
 ConnectAsViewer = 'kinesisvideo:ConnectAsViewer',
 CreateSignalingChannel = 'kinesisvideo:CreateSignalingChannel',
 CreateStream = 'kinesisvideo:CreateStream',
 DeleteSignalingChannel = 'kinesisvideo:DeleteSignalingChannel',
 DeleteStream = 'kinesisvideo:DeleteStream',
 DescribeSignalingChannel = 'kinesisvideo:DescribeSignalingChannel',
 DescribeStream = 'kinesisvideo:DescribeStream',
 GetClip = 'kinesisvideo:GetClip',
 GetDASHStreamingSessionURL = 'kinesisvideo:GetDASHStreamingSessionURL',
 GetDataEndpoint = 'kinesisvideo:GetDataEndpoint',
 GetHLSStreamingSessionURL = 'kinesisvideo:GetHLSStreamingSessionURL',
 GetIceServerConfig = 'kinesisvideo:GetIceServerConfig',
 GetMedia = 'kinesisvideo:GetMedia',
 GetMediaForFragmentList = 'kinesisvideo:GetMediaForFragmentList',
 GetSignalingChannelEndpoint = 'kinesisvideo:GetSignalingChannelEndpoint',
 ListFragments = 'kinesisvideo:ListFragments',
 ListSignalingChannels = 'kinesisvideo:ListSignalingChannels',
 ListStreams = 'kinesisvideo:ListStreams',
 ListTagsForResource = 'kinesisvideo:ListTagsForResource',
 ListTagsForStream = 'kinesisvideo:ListTagsForStream',
 PutMedia = 'kinesisvideo:PutMedia',
 SendAlexaOfferToMaster = 'kinesisvideo:SendAlexaOfferToMaster',
 TagResource = 'kinesisvideo:TagResource',
 TagStream = 'kinesisvideo:TagStream',
 UntagResource = 'kinesisvideo:UntagResource',
 UntagStream = 'kinesisvideo:UntagStream',
 UpdateDataRetention = 'kinesisvideo:UpdateDataRetention',
 UpdateSignalingChannel = 'kinesisvideo:UpdateSignalingChannel',
 UpdateStream = 'kinesisvideo:UpdateStream',

}