
export enum machinelearning {
 AddTags = 'machinelearning:AddTags',
 CreateBatchPrediction = 'machinelearning:CreateBatchPrediction',
 CreateDataSourceFromRDS = 'machinelearning:CreateDataSourceFromRDS',
 CreateDataSourceFromRedshift = 'machinelearning:CreateDataSourceFromRedshift',
 CreateDataSourceFromS3 = 'machinelearning:CreateDataSourceFromS3',
 CreateEvaluation = 'machinelearning:CreateEvaluation',
 CreateMLModel = 'machinelearning:CreateMLModel',
 CreateRealtimeEndpoint = 'machinelearning:CreateRealtimeEndpoint',
 DeleteBatchPrediction = 'machinelearning:DeleteBatchPrediction',
 DeleteDataSource = 'machinelearning:DeleteDataSource',
 DeleteEvaluation = 'machinelearning:DeleteEvaluation',
 DeleteMLModel = 'machinelearning:DeleteMLModel',
 DeleteRealtimeEndpoint = 'machinelearning:DeleteRealtimeEndpoint',
 DeleteTags = 'machinelearning:DeleteTags',
 DescribeBatchPredictions = 'machinelearning:DescribeBatchPredictions',
 DescribeDataSources = 'machinelearning:DescribeDataSources',
 DescribeEvaluations = 'machinelearning:DescribeEvaluations',
 DescribeMLModels = 'machinelearning:DescribeMLModels',
 DescribeTags = 'machinelearning:DescribeTags',
 GetBatchPrediction = 'machinelearning:GetBatchPrediction',
 GetDataSource = 'machinelearning:GetDataSource',
 GetEvaluation = 'machinelearning:GetEvaluation',
 GetMLModel = 'machinelearning:GetMLModel',
 Predict = 'machinelearning:Predict',
 UpdateBatchPrediction = 'machinelearning:UpdateBatchPrediction',
 UpdateDataSource = 'machinelearning:UpdateDataSource',
 UpdateEvaluation = 'machinelearning:UpdateEvaluation',
 UpdateMLModel = 'machinelearning:UpdateMLModel',

}