
export enum mechanicalturk {
 AcceptQualificationRequest = 'mechanicalturk:AcceptQualificationRequest',
 ApproveAssignment = 'mechanicalturk:ApproveAssignment',
 AssociateQualificationWithWorker = 'mechanicalturk:AssociateQualificationWithWorker',
 CreateAdditionalAssignmentsForHIT = 'mechanicalturk:CreateAdditionalAssignmentsForHIT',
 CreateHIT = 'mechanicalturk:CreateHIT',
 CreateHITType = 'mechanicalturk:CreateHITType',
 CreateHITWithHITType = 'mechanicalturk:CreateHITWithHITType',
 CreateQualificationType = 'mechanicalturk:CreateQualificationType',
 CreateWorkerBlock = 'mechanicalturk:CreateWorkerBlock',
 DeleteHIT = 'mechanicalturk:DeleteHIT',
 DeleteQualificationType = 'mechanicalturk:DeleteQualificationType',
 DeleteWorkerBlock = 'mechanicalturk:DeleteWorkerBlock',
 DisassociateQualificationFromWorker = 'mechanicalturk:DisassociateQualificationFromWorker',
 GetAccountBalance = 'mechanicalturk:GetAccountBalance',
 GetAssignment = 'mechanicalturk:GetAssignment',
 GetFileUploadURL = 'mechanicalturk:GetFileUploadURL',
 GetHIT = 'mechanicalturk:GetHIT',
 GetQualificationScore = 'mechanicalturk:GetQualificationScore',
 GetQualificationType = 'mechanicalturk:GetQualificationType',
 ListAssignmentsForHIT = 'mechanicalturk:ListAssignmentsForHIT',
 ListBonusPayments = 'mechanicalturk:ListBonusPayments',
 ListHITs = 'mechanicalturk:ListHITs',
 ListHITsForQualificationType = 'mechanicalturk:ListHITsForQualificationType',
 ListQualificationRequests = 'mechanicalturk:ListQualificationRequests',
 ListQualificationTypes = 'mechanicalturk:ListQualificationTypes',
 ListReviewPolicyResultsForHIT = 'mechanicalturk:ListReviewPolicyResultsForHIT',
 ListReviewableHITs = 'mechanicalturk:ListReviewableHITs',
 ListWorkerBlocks = 'mechanicalturk:ListWorkerBlocks',
 ListWorkersWithQualificationType = 'mechanicalturk:ListWorkersWithQualificationType',
 NotifyWorkers = 'mechanicalturk:NotifyWorkers',
 RejectAssignment = 'mechanicalturk:RejectAssignment',
 RejectQualificationRequest = 'mechanicalturk:RejectQualificationRequest',
 SendBonus = 'mechanicalturk:SendBonus',
 SendTestEventNotification = 'mechanicalturk:SendTestEventNotification',
 UpdateExpirationForHIT = 'mechanicalturk:UpdateExpirationForHIT',
 UpdateHITReviewStatus = 'mechanicalturk:UpdateHITReviewStatus',
 UpdateHITTypeOfHIT = 'mechanicalturk:UpdateHITTypeOfHIT',
 UpdateNotificationSettings = 'mechanicalturk:UpdateNotificationSettings',
 UpdateQualificationType = 'mechanicalturk:UpdateQualificationType',

}