
export enum mediaconvert {
 AssociateCertificate = 'mediaconvert:AssociateCertificate',
 CancelJob = 'mediaconvert:CancelJob',
 CreateJob = 'mediaconvert:CreateJob',
 CreateJobTemplate = 'mediaconvert:CreateJobTemplate',
 CreatePreset = 'mediaconvert:CreatePreset',
 CreateQueue = 'mediaconvert:CreateQueue',
 DeleteJobTemplate = 'mediaconvert:DeleteJobTemplate',
 DeletePreset = 'mediaconvert:DeletePreset',
 DeleteQueue = 'mediaconvert:DeleteQueue',
 DescribeEndpoints = 'mediaconvert:DescribeEndpoints',
 DisassociateCertificate = 'mediaconvert:DisassociateCertificate',
 GetJob = 'mediaconvert:GetJob',
 GetJobTemplate = 'mediaconvert:GetJobTemplate',
 GetPreset = 'mediaconvert:GetPreset',
 GetQueue = 'mediaconvert:GetQueue',
 ListJobTemplates = 'mediaconvert:ListJobTemplates',
 ListJobs = 'mediaconvert:ListJobs',
 ListPresets = 'mediaconvert:ListPresets',
 ListQueues = 'mediaconvert:ListQueues',
 ListTagsForResource = 'mediaconvert:ListTagsForResource',
 TagResource = 'mediaconvert:TagResource',
 UntagResource = 'mediaconvert:UntagResource',
 UpdateJobTemplate = 'mediaconvert:UpdateJobTemplate',
 UpdatePreset = 'mediaconvert:UpdatePreset',
 UpdateQueue = 'mediaconvert:UpdateQueue',

}