
export enum mediapackage {
 All = 'mediapackage:*',
 Create = 'mediapackage:Create*',
 Delete = 'mediapackage:Delete*',
 Describe = 'mediapackage:Describe*',
 List = 'mediapackage:List*',
 Update = 'mediapackage:Update*',
 CreateChannel = 'mediapackage:CreateChannel',
 CreateHarvestJob = 'mediapackage:CreateHarvestJob',
 CreateOriginEndpoint = 'mediapackage:CreateOriginEndpoint',
 DeleteChannel = 'mediapackage:DeleteChannel',
 DeleteOriginEndpoint = 'mediapackage:DeleteOriginEndpoint',
 DescribeChannel = 'mediapackage:DescribeChannel',
 DescribeHarvestJob = 'mediapackage:DescribeHarvestJob',
 DescribeOriginEndpoint = 'mediapackage:DescribeOriginEndpoint',
 ListChannels = 'mediapackage:ListChannels',
 ListHarvestJobs = 'mediapackage:ListHarvestJobs',
 ListOriginEndpoints = 'mediapackage:ListOriginEndpoints',
 ListTagsForResource = 'mediapackage:ListTagsForResource',
 RotateIngestEndpointCredentials = 'mediapackage:RotateIngestEndpointCredentials',
 TagResource = 'mediapackage:TagResource',
 UntagResource = 'mediapackage:UntagResource',
 UpdateChannel = 'mediapackage:UpdateChannel',
 UpdateOriginEndpoint = 'mediapackage:UpdateOriginEndpoint',

}