
export enum mediastore {
 CreateContainer = 'mediastore:CreateContainer',
 DeleteContainer = 'mediastore:DeleteContainer',
 DeleteContainerPolicy = 'mediastore:DeleteContainerPolicy',
 DeleteCorsPolicy = 'mediastore:DeleteCorsPolicy',
 DeleteLifecyclePolicy = 'mediastore:DeleteLifecyclePolicy',
 DeleteMetricPolicy = 'mediastore:DeleteMetricPolicy',
 DeleteObject = 'mediastore:DeleteObject',
 DescribeContainer = 'mediastore:DescribeContainer',
 DescribeObject = 'mediastore:DescribeObject',
 GetContainerPolicy = 'mediastore:GetContainerPolicy',
 GetCorsPolicy = 'mediastore:GetCorsPolicy',
 GetLifecyclePolicy = 'mediastore:GetLifecyclePolicy',
 GetMetricPolicy = 'mediastore:GetMetricPolicy',
 GetObject = 'mediastore:GetObject',
 ListContainers = 'mediastore:ListContainers',
 ListItems = 'mediastore:ListItems',
 ListTagsForResource = 'mediastore:ListTagsForResource',
 PutContainerPolicy = 'mediastore:PutContainerPolicy',
 PutCorsPolicy = 'mediastore:PutCorsPolicy',
 PutLifecyclePolicy = 'mediastore:PutLifecyclePolicy',
 PutMetricPolicy = 'mediastore:PutMetricPolicy',
 PutObject = 'mediastore:PutObject',
 StartAccessLogging = 'mediastore:StartAccessLogging',
 StopAccessLogging = 'mediastore:StopAccessLogging',
 TagResource = 'mediastore:TagResource',
 UntagResource = 'mediastore:UntagResource',

}