
export enum mgh {
 All = 'mgh:*',
 Associate = 'mgh:Associate*',
 Create = 'mgh:Create*',
 Describe = 'mgh:Describe*',
 Disassociate = 'mgh:Disassociate*',
 List = 'mgh:List*',
 Notify = 'mgh:Notify*',
 AssociateCreatedArtifact = 'mgh:AssociateCreatedArtifact',
 AssociateDiscoveredResource = 'mgh:AssociateDiscoveredResource',
 CreateHomeRegionControl = 'mgh:CreateHomeRegionControl',
 CreateProgressUpdateStream = 'mgh:CreateProgressUpdateStream',
 DeleteProgressUpdateStream = 'mgh:DeleteProgressUpdateStream',
 DescribeApplicationState = 'mgh:DescribeApplicationState',
 DescribeHomeRegionControls = 'mgh:DescribeHomeRegionControls',
 DescribeMigrationTask = 'mgh:DescribeMigrationTask',
 DisassociateCreatedArtifact = 'mgh:DisassociateCreatedArtifact',
 DisassociateDiscoveredResource = 'mgh:DisassociateDiscoveredResource',
 GetHomeRegion = 'mgh:GetHomeRegion',
 ImportMigrationTask = 'mgh:ImportMigrationTask',
 ListCreatedArtifacts = 'mgh:ListCreatedArtifacts',
 ListDiscoveredResources = 'mgh:ListDiscoveredResources',
 ListMigrationTasks = 'mgh:ListMigrationTasks',
 ListProgressUpdateStreams = 'mgh:ListProgressUpdateStreams',
 NotifyApplicationState = 'mgh:NotifyApplicationState',
 NotifyMigrationTaskState = 'mgh:NotifyMigrationTaskState',
 PutResourceAttributes = 'mgh:PutResourceAttributes',

}