
export enum networkmanager {
 AssociateCustomerGateway = 'networkmanager:AssociateCustomerGateway',
 AssociateLink = 'networkmanager:AssociateLink',
 AssociateTransitGatewayConnectPeer = 'networkmanager:AssociateTransitGatewayConnectPeer',
 CreateConnection = 'networkmanager:CreateConnection',
 CreateDevice = 'networkmanager:CreateDevice',
 CreateGlobalNetwork = 'networkmanager:CreateGlobalNetwork',
 CreateLink = 'networkmanager:CreateLink',
 CreateSite = 'networkmanager:CreateSite',
 DeleteConnection = 'networkmanager:DeleteConnection',
 DeleteDevice = 'networkmanager:DeleteDevice',
 DeleteGlobalNetwork = 'networkmanager:DeleteGlobalNetwork',
 DeleteLink = 'networkmanager:DeleteLink',
 DeleteSite = 'networkmanager:DeleteSite',
 DeregisterTransitGateway = 'networkmanager:DeregisterTransitGateway',
 DescribeGlobalNetworks = 'networkmanager:DescribeGlobalNetworks',
 DisassociateCustomerGateway = 'networkmanager:DisassociateCustomerGateway',
 DisassociateLink = 'networkmanager:DisassociateLink',
 DisassociateTransitGatewayConnectPeer = 'networkmanager:DisassociateTransitGatewayConnectPeer',
 GetConnections = 'networkmanager:GetConnections',
 GetCustomerGatewayAssociations = 'networkmanager:GetCustomerGatewayAssociations',
 GetDevices = 'networkmanager:GetDevices',
 GetLinkAssociations = 'networkmanager:GetLinkAssociations',
 GetLinks = 'networkmanager:GetLinks',
 GetSites = 'networkmanager:GetSites',
 GetTransitGatewayConnectPeerAssociations = 'networkmanager:GetTransitGatewayConnectPeerAssociations',
 GetTransitGatewayRegistrations = 'networkmanager:GetTransitGatewayRegistrations',
 ListTagsForResource = 'networkmanager:ListTagsForResource',
 RegisterTransitGateway = 'networkmanager:RegisterTransitGateway',
 TagResource = 'networkmanager:TagResource',
 UntagResource = 'networkmanager:UntagResource',
 UpdateConnection = 'networkmanager:UpdateConnection',
 UpdateDevice = 'networkmanager:UpdateDevice',
 UpdateGlobalNetwork = 'networkmanager:UpdateGlobalNetwork',
 UpdateLink = 'networkmanager:UpdateLink',
 UpdateSite = 'networkmanager:UpdateSite',

}