
export enum network_firewall {
 All = 'network-firewall:*',
 Associate = 'network-firewall:Associate*',
 Create = 'network-firewall:Create*',
 Delete = 'network-firewall:Delete*',
 Describe = 'network-firewall:Describe*',
 List = 'network-firewall:List*',
 Update = 'network-firewall:Update*',
 AssociateFirewallPolicy = 'network-firewall:AssociateFirewallPolicy',
 AssociateSubnets = 'network-firewall:AssociateSubnets',
 CreateFirewall = 'network-firewall:CreateFirewall',
 CreateFirewallPolicy = 'network-firewall:CreateFirewallPolicy',
 CreateRuleGroup = 'network-firewall:CreateRuleGroup',
 DeleteFirewall = 'network-firewall:DeleteFirewall',
 DeleteFirewallPolicy = 'network-firewall:DeleteFirewallPolicy',
 DeleteResourcePolicy = 'network-firewall:DeleteResourcePolicy',
 DeleteRuleGroup = 'network-firewall:DeleteRuleGroup',
 DescribeFirewall = 'network-firewall:DescribeFirewall',
 DescribeFirewallPolicy = 'network-firewall:DescribeFirewallPolicy',
 DescribeLoggingConfiguration = 'network-firewall:DescribeLoggingConfiguration',
 DescribeResourcePolicy = 'network-firewall:DescribeResourcePolicy',
 DescribeRuleGroup = 'network-firewall:DescribeRuleGroup',
 DisassociateSubnets = 'network-firewall:DisassociateSubnets',
 ListFirewallPolicies = 'network-firewall:ListFirewallPolicies',
 ListFirewalls = 'network-firewall:ListFirewalls',
 ListRuleGroups = 'network-firewall:ListRuleGroups',
 ListTagsForResource = 'network-firewall:ListTagsForResource',
 PutResourcePolicy = 'network-firewall:PutResourcePolicy',
 TagResource = 'network-firewall:TagResource',
 UntagResource = 'network-firewall:UntagResource',
 UpdateFirewallDeleteProtection = 'network-firewall:UpdateFirewallDeleteProtection',
 UpdateFirewallDescription = 'network-firewall:UpdateFirewallDescription',
 UpdateFirewallPolicy = 'network-firewall:UpdateFirewallPolicy',
 UpdateFirewallPolicyChangeProtection = 'network-firewall:UpdateFirewallPolicyChangeProtection',
 UpdateLoggingConfiguration = 'network-firewall:UpdateLoggingConfiguration',
 UpdateRuleGroup = 'network-firewall:UpdateRuleGroup',
 UpdateSubnetChangeProtection = 'network-firewall:UpdateSubnetChangeProtection',

}