
export enum opsworks_cm {
 All = 'opsworks-cm:*',
 Create = 'opsworks-cm:Create*',
 Delete = 'opsworks-cm:Delete*',
 Describe = 'opsworks-cm:Describe*',
 Update = 'opsworks-cm:Update*',
 AssociateNode = 'opsworks-cm:AssociateNode',
 CreateBackup = 'opsworks-cm:CreateBackup',
 CreateServer = 'opsworks-cm:CreateServer',
 DeleteBackup = 'opsworks-cm:DeleteBackup',
 DeleteServer = 'opsworks-cm:DeleteServer',
 DescribeAccountAttributes = 'opsworks-cm:DescribeAccountAttributes',
 DescribeBackups = 'opsworks-cm:DescribeBackups',
 DescribeEvents = 'opsworks-cm:DescribeEvents',
 DescribeNodeAssociationStatus = 'opsworks-cm:DescribeNodeAssociationStatus',
 DescribeServers = 'opsworks-cm:DescribeServers',
 DisassociateNode = 'opsworks-cm:DisassociateNode',
 ListTagsForResource = 'opsworks-cm:ListTagsForResource',
 RestoreServer = 'opsworks-cm:RestoreServer',
 StartMaintenance = 'opsworks-cm:StartMaintenance',
 TagResource = 'opsworks-cm:TagResource',
 UntagResource = 'opsworks-cm:UntagResource',
 UpdateServer = 'opsworks-cm:UpdateServer',
 UpdateServerEngineAttributes = 'opsworks-cm:UpdateServerEngineAttributes',

}