
export enum profile {
 All = 'profile:*',
 Create = 'profile:Create*',
 Delete = 'profile:Delete*',
 Get = 'profile:Get*',
 List = 'profile:List*',
 Put = 'profile:Put*',
 Update = 'profile:Update*',
 AddProfileKey = 'profile:AddProfileKey',
 CreateDomain = 'profile:CreateDomain',
 CreateProfile = 'profile:CreateProfile',
 DeleteDomain = 'profile:DeleteDomain',
 DeleteIntegration = 'profile:DeleteIntegration',
 DeleteProfile = 'profile:DeleteProfile',
 DeleteProfileKey = 'profile:DeleteProfileKey',
 DeleteProfileObject = 'profile:DeleteProfileObject',
 DeleteProfileObjectType = 'profile:DeleteProfileObjectType',
 GetDomain = 'profile:GetDomain',
 GetIntegration = 'profile:GetIntegration',
 GetProfileObjectType = 'profile:GetProfileObjectType',
 GetProfileObjectTypeTemplate = 'profile:GetProfileObjectTypeTemplate',
 ListAccountIntegrations = 'profile:ListAccountIntegrations',
 ListDomains = 'profile:ListDomains',
 ListIntegrations = 'profile:ListIntegrations',
 ListProfileObjectTypeTemplates = 'profile:ListProfileObjectTypeTemplates',
 ListProfileObjectTypes = 'profile:ListProfileObjectTypes',
 ListProfileObjects = 'profile:ListProfileObjects',
 ListTagsForResource = 'profile:ListTagsForResource',
 PutIntegration = 'profile:PutIntegration',
 PutProfileObject = 'profile:PutProfileObject',
 PutProfileObjectType = 'profile:PutProfileObjectType',
 SearchProfiles = 'profile:SearchProfiles',
 TagResource = 'profile:TagResource',
 UntagResource = 'profile:UntagResource',
 UpdateDomain = 'profile:UpdateDomain',
 UpdateProfile = 'profile:UpdateProfile',

}