
export enum qldb {
 All = 'qldb:*',
 Describe = 'qldb:Describe*',
 Get = 'qldb:Get*',
 List = 'qldb:List*',
 CancelJournalKinesisStream = 'qldb:CancelJournalKinesisStream',
 CreateLedger = 'qldb:CreateLedger',
 DeleteLedger = 'qldb:DeleteLedger',
 DescribeJournalKinesisStream = 'qldb:DescribeJournalKinesisStream',
 DescribeJournalS3Export = 'qldb:DescribeJournalS3Export',
 DescribeLedger = 'qldb:DescribeLedger',
 ExecuteStatement = 'qldb:ExecuteStatement',
 ExportJournalToS3 = 'qldb:ExportJournalToS3',
 GetBlock = 'qldb:GetBlock',
 GetDigest = 'qldb:GetDigest',
 GetRevision = 'qldb:GetRevision',
 InsertSampleData = 'qldb:InsertSampleData',
 ListJournalKinesisStreamsForLedger = 'qldb:ListJournalKinesisStreamsForLedger',
 ListJournalS3Exports = 'qldb:ListJournalS3Exports',
 ListJournalS3ExportsForLedger = 'qldb:ListJournalS3ExportsForLedger',
 ListLedgers = 'qldb:ListLedgers',
 ListTagsForResource = 'qldb:ListTagsForResource',
 SendCommand = 'qldb:SendCommand',
 ShowCatalog = 'qldb:ShowCatalog',
 StreamJournalToKinesis = 'qldb:StreamJournalToKinesis',
 TagResource = 'qldb:TagResource',
 UntagResource = 'qldb:UntagResource',
 UpdateLedger = 'qldb:UpdateLedger',

}