
export enum route53resolver {
 All = 'route53resolver:*',
 Associate = 'route53resolver:Associate*',
 Create = 'route53resolver:Create*',
 Delete = 'route53resolver:Delete*',
 Disassociate = 'route53resolver:Disassociate*',
 Get = 'route53resolver:Get*',
 List = 'route53resolver:List*',
 Put = 'route53resolver:Put*',
 Update = 'route53resolver:Update*',
 AssociateResolverEndpointIpAddress = 'route53resolver:AssociateResolverEndpointIpAddress',
 AssociateResolverQueryLogConfig = 'route53resolver:AssociateResolverQueryLogConfig',
 AssociateResolverRule = 'route53resolver:AssociateResolverRule',
 CreateResolverEndpoint = 'route53resolver:CreateResolverEndpoint',
 CreateResolverQueryLogConfig = 'route53resolver:CreateResolverQueryLogConfig',
 CreateResolverRule = 'route53resolver:CreateResolverRule',
 DeleteResolverEndpoint = 'route53resolver:DeleteResolverEndpoint',
 DeleteResolverQueryLogConfig = 'route53resolver:DeleteResolverQueryLogConfig',
 DeleteResolverRule = 'route53resolver:DeleteResolverRule',
 DisassociateResolverEndpointIpAddress = 'route53resolver:DisassociateResolverEndpointIpAddress',
 DisassociateResolverQueryLogConfig = 'route53resolver:DisassociateResolverQueryLogConfig',
 DisassociateResolverRule = 'route53resolver:DisassociateResolverRule',
 GetResolverDnssecConfig = 'route53resolver:GetResolverDnssecConfig',
 GetResolverEndpoint = 'route53resolver:GetResolverEndpoint',
 GetResolverQueryLogConfig = 'route53resolver:GetResolverQueryLogConfig',
 GetResolverQueryLogConfigAssociation = 'route53resolver:GetResolverQueryLogConfigAssociation',
 GetResolverQueryLogConfigPolicy = 'route53resolver:GetResolverQueryLogConfigPolicy',
 GetResolverRule = 'route53resolver:GetResolverRule',
 GetResolverRuleAssociation = 'route53resolver:GetResolverRuleAssociation',
 GetResolverRulePolicy = 'route53resolver:GetResolverRulePolicy',
 ListResolverDnssecConfigs = 'route53resolver:ListResolverDnssecConfigs',
 ListResolverEndpointIpAddresses = 'route53resolver:ListResolverEndpointIpAddresses',
 ListResolverEndpoints = 'route53resolver:ListResolverEndpoints',
 ListResolverQueryLogConfigAssociations = 'route53resolver:ListResolverQueryLogConfigAssociations',
 ListResolverQueryLogConfigs = 'route53resolver:ListResolverQueryLogConfigs',
 ListResolverRuleAssociations = 'route53resolver:ListResolverRuleAssociations',
 ListResolverRules = 'route53resolver:ListResolverRules',
 ListTagsForResource = 'route53resolver:ListTagsForResource',
 PutResolverQueryLogConfigPolicy = 'route53resolver:PutResolverQueryLogConfigPolicy',
 PutResolverRulePolicy = 'route53resolver:PutResolverRulePolicy',
 TagResource = 'route53resolver:TagResource',
 UntagResource = 'route53resolver:UntagResource',
 UpdateResolverDnssecConfig = 'route53resolver:UpdateResolverDnssecConfig',
 UpdateResolverEndpoint = 'route53resolver:UpdateResolverEndpoint',
 UpdateResolverRule = 'route53resolver:UpdateResolverRule',

}