
export enum route53domains {
 CheckDomainAvailability = 'route53domains:CheckDomainAvailability',
 DeleteTagsForDomain = 'route53domains:DeleteTagsForDomain',
 DisableDomainAutoRenew = 'route53domains:DisableDomainAutoRenew',
 DisableDomainTransferLock = 'route53domains:DisableDomainTransferLock',
 EnableDomainAutoRenew = 'route53domains:EnableDomainAutoRenew',
 EnableDomainTransferLock = 'route53domains:EnableDomainTransferLock',
 GetContactReachabilityStatus = 'route53domains:GetContactReachabilityStatus',
 GetDomainDetail = 'route53domains:GetDomainDetail',
 GetDomainSuggestions = 'route53domains:GetDomainSuggestions',
 GetOperationDetail = 'route53domains:GetOperationDetail',
 ListDomains = 'route53domains:ListDomains',
 ListOperations = 'route53domains:ListOperations',
 ListTagsForDomain = 'route53domains:ListTagsForDomain',
 RegisterDomain = 'route53domains:RegisterDomain',
 RenewDomain = 'route53domains:RenewDomain',
 ResendContactReachabilityEmail = 'route53domains:ResendContactReachabilityEmail',
 RetrieveDomainAuthCode = 'route53domains:RetrieveDomainAuthCode',
 TransferDomain = 'route53domains:TransferDomain',
 UpdateDomainContact = 'route53domains:UpdateDomainContact',
 UpdateDomainContactPrivacy = 'route53domains:UpdateDomainContactPrivacy',
 UpdateDomainNameservers = 'route53domains:UpdateDomainNameservers',
 UpdateTagsForDomain = 'route53domains:UpdateTagsForDomain',
 ViewBilling = 'route53domains:ViewBilling',

}