
export enum s3_outposts {
 All = 's3-outposts:*',
 Create = 's3-outposts:Create*',
 Delete = 's3-outposts:Delete*',
 Get = 's3-outposts:Get*',
 List = 's3-outposts:List*',
 Put = 's3-outposts:Put*',
 AbortMultipartUpload = 's3-outposts:AbortMultipartUpload',
 CreateAccessPoint = 's3-outposts:CreateAccessPoint',
 CreateBucket = 's3-outposts:CreateBucket',
 CreateEndpoint = 's3-outposts:CreateEndpoint',
 DeleteAccessPoint = 's3-outposts:DeleteAccessPoint',
 DeleteAccessPointPolicy = 's3-outposts:DeleteAccessPointPolicy',
 DeleteBucket = 's3-outposts:DeleteBucket',
 DeleteBucketPolicy = 's3-outposts:DeleteBucketPolicy',
 DeleteEndpoint = 's3-outposts:DeleteEndpoint',
 DeleteObject = 's3-outposts:DeleteObject',
 DeleteObjectTagging = 's3-outposts:DeleteObjectTagging',
 GetAccessPoint = 's3-outposts:GetAccessPoint',
 GetAccessPointPolicy = 's3-outposts:GetAccessPointPolicy',
 GetBucket = 's3-outposts:GetBucket',
 GetBucketPolicy = 's3-outposts:GetBucketPolicy',
 GetBucketTagging = 's3-outposts:GetBucketTagging',
 GetLifecycleConfiguration = 's3-outposts:GetLifecycleConfiguration',
 GetObject = 's3-outposts:GetObject',
 GetObjectTagging = 's3-outposts:GetObjectTagging',
 ListAccessPoints = 's3-outposts:ListAccessPoints',
 ListBucket = 's3-outposts:ListBucket',
 ListBucketMultipartUploads = 's3-outposts:ListBucketMultipartUploads',
 ListEndpoints = 's3-outposts:ListEndpoints',
 ListMultipartUploadParts = 's3-outposts:ListMultipartUploadParts',
 ListRegionalBuckets = 's3-outposts:ListRegionalBuckets',
 PutAccessPointPolicy = 's3-outposts:PutAccessPointPolicy',
 PutBucketPolicy = 's3-outposts:PutBucketPolicy',
 PutBucketTagging = 's3-outposts:PutBucketTagging',
 PutLifecycleConfiguration = 's3-outposts:PutLifecycleConfiguration',
 PutObject = 's3-outposts:PutObject',
 PutObjectAcl = 's3-outposts:PutObjectAcl',
 PutObjectTagging = 's3-outposts:PutObjectTagging',

}