
export enum schemas {
 All = 'schemas:*',
 Create = 'schemas:Create*',
 Delete = 'schemas:Delete*',
 Describe = 'schemas:Describe*',
 Get = 'schemas:Get*',
 List = 'schemas:List*',
 Put = 'schemas:Put*',
 Update = 'schemas:Update*',
 CreateDiscoverer = 'schemas:CreateDiscoverer',
 CreateRegistry = 'schemas:CreateRegistry',
 CreateSchema = 'schemas:CreateSchema',
 DeleteDiscoverer = 'schemas:DeleteDiscoverer',
 DeleteRegistry = 'schemas:DeleteRegistry',
 DeleteResourcePolicy = 'schemas:DeleteResourcePolicy',
 DeleteSchema = 'schemas:DeleteSchema',
 DeleteSchemaVersion = 'schemas:DeleteSchemaVersion',
 DescribeCodeBinding = 'schemas:DescribeCodeBinding',
 DescribeDiscoverer = 'schemas:DescribeDiscoverer',
 DescribeRegistry = 'schemas:DescribeRegistry',
 DescribeSchema = 'schemas:DescribeSchema',
 ExportSchema = 'schemas:ExportSchema',
 GetCodeBindingSource = 'schemas:GetCodeBindingSource',
 GetDiscoveredSchema = 'schemas:GetDiscoveredSchema',
 GetResourcePolicy = 'schemas:GetResourcePolicy',
 ListDiscoverers = 'schemas:ListDiscoverers',
 ListRegistries = 'schemas:ListRegistries',
 ListSchemaVersions = 'schemas:ListSchemaVersions',
 ListSchemas = 'schemas:ListSchemas',
 ListTagsForResource = 'schemas:ListTagsForResource',
 PutCodeBinding = 'schemas:PutCodeBinding',
 PutResourcePolicy = 'schemas:PutResourcePolicy',
 SearchSchemas = 'schemas:SearchSchemas',
 StartDiscoverer = 'schemas:StartDiscoverer',
 StopDiscoverer = 'schemas:StopDiscoverer',
 TagResource = 'schemas:TagResource',
 UntagResource = 'schemas:UntagResource',
 UpdateDiscoverer = 'schemas:UpdateDiscoverer',
 UpdateRegistry = 'schemas:UpdateRegistry',
 UpdateSchema = 'schemas:UpdateSchema',

}