
export enum secretsmanager {
 All = 'secretsmanager:*',
 Delete = 'secretsmanager:Delete*',
 Get = 'secretsmanager:Get*',
 List = 'secretsmanager:List*',
 Put = 'secretsmanager:Put*',
 Update = 'secretsmanager:Update*',
 CancelRotateSecret = 'secretsmanager:CancelRotateSecret',
 CreateSecret = 'secretsmanager:CreateSecret',
 DeleteResourcePolicy = 'secretsmanager:DeleteResourcePolicy',
 DeleteSecret = 'secretsmanager:DeleteSecret',
 DescribeSecret = 'secretsmanager:DescribeSecret',
 GetRandomPassword = 'secretsmanager:GetRandomPassword',
 GetResourcePolicy = 'secretsmanager:GetResourcePolicy',
 GetSecretValue = 'secretsmanager:GetSecretValue',
 ListSecretVersionIds = 'secretsmanager:ListSecretVersionIds',
 ListSecrets = 'secretsmanager:ListSecrets',
 PutResourcePolicy = 'secretsmanager:PutResourcePolicy',
 PutSecretValue = 'secretsmanager:PutSecretValue',
 RestoreSecret = 'secretsmanager:RestoreSecret',
 RotateSecret = 'secretsmanager:RotateSecret',
 TagResource = 'secretsmanager:TagResource',
 UntagResource = 'secretsmanager:UntagResource',
 UpdateSecret = 'secretsmanager:UpdateSecret',
 UpdateSecretVersionStage = 'secretsmanager:UpdateSecretVersionStage',
 ValidateResourcePolicy = 'secretsmanager:ValidateResourcePolicy',

}