
export enum servicequotas {
 All = 'servicequotas:*',
 Get = 'servicequotas:Get*',
 List = 'servicequotas:List*',
 AssociateServiceQuotaTemplate = 'servicequotas:AssociateServiceQuotaTemplate',
 DeleteServiceQuotaIncreaseRequestFromTemplate = 'servicequotas:DeleteServiceQuotaIncreaseRequestFromTemplate',
 DisassociateServiceQuotaTemplate = 'servicequotas:DisassociateServiceQuotaTemplate',
 GetAWSDefaultServiceQuota = 'servicequotas:GetAWSDefaultServiceQuota',
 GetAssociationForServiceQuotaTemplate = 'servicequotas:GetAssociationForServiceQuotaTemplate',
 GetRequestedServiceQuotaChange = 'servicequotas:GetRequestedServiceQuotaChange',
 GetServiceQuota = 'servicequotas:GetServiceQuota',
 GetServiceQuotaIncreaseRequestFromTemplate = 'servicequotas:GetServiceQuotaIncreaseRequestFromTemplate',
 ListAWSDefaultServiceQuotas = 'servicequotas:ListAWSDefaultServiceQuotas',
 ListRequestedServiceQuotaChangeHistory = 'servicequotas:ListRequestedServiceQuotaChangeHistory',
 ListRequestedServiceQuotaChangeHistoryByQuota = 'servicequotas:ListRequestedServiceQuotaChangeHistoryByQuota',
 ListServiceQuotaIncreaseRequestsInTemplate = 'servicequotas:ListServiceQuotaIncreaseRequestsInTemplate',
 ListServiceQuotas = 'servicequotas:ListServiceQuotas',
 ListServices = 'servicequotas:ListServices',
 ListTagsForResource = 'servicequotas:ListTagsForResource',
 PutServiceQuotaIncreaseRequestIntoTemplate = 'servicequotas:PutServiceQuotaIncreaseRequestIntoTemplate',
 RequestServiceQuotaIncrease = 'servicequotas:RequestServiceQuotaIncrease',
 TagResource = 'servicequotas:TagResource',
 UntagResource = 'servicequotas:UntagResource',

}