
export enum sms {
 CreateApp = 'sms:CreateApp',
 CreateReplicationJob = 'sms:CreateReplicationJob',
 DeleteApp = 'sms:DeleteApp',
 DeleteAppLaunchConfiguration = 'sms:DeleteAppLaunchConfiguration',
 DeleteAppReplicationConfiguration = 'sms:DeleteAppReplicationConfiguration',
 DeleteAppValidationConfiguration = 'sms:DeleteAppValidationConfiguration',
 DeleteReplicationJob = 'sms:DeleteReplicationJob',
 DeleteServerCatalog = 'sms:DeleteServerCatalog',
 DisassociateConnector = 'sms:DisassociateConnector',
 GenerateChangeSet = 'sms:GenerateChangeSet',
 GenerateTemplate = 'sms:GenerateTemplate',
 GetApp = 'sms:GetApp',
 GetAppLaunchConfiguration = 'sms:GetAppLaunchConfiguration',
 GetAppReplicationConfiguration = 'sms:GetAppReplicationConfiguration',
 GetAppValidationConfiguration = 'sms:GetAppValidationConfiguration',
 GetAppValidationOutput = 'sms:GetAppValidationOutput',
 GetConnectors = 'sms:GetConnectors',
 GetMessages = 'sms:GetMessages',
 GetReplicationJobs = 'sms:GetReplicationJobs',
 GetReplicationRuns = 'sms:GetReplicationRuns',
 GetServers = 'sms:GetServers',
 ImportAppCatalog = 'sms:ImportAppCatalog',
 ImportServerCatalog = 'sms:ImportServerCatalog',
 LaunchApp = 'sms:LaunchApp',
 ListApps = 'sms:ListApps',
 NotifyAppValidationOutput = 'sms:NotifyAppValidationOutput',
 PutAppLaunchConfiguration = 'sms:PutAppLaunchConfiguration',
 PutAppReplicationConfiguration = 'sms:PutAppReplicationConfiguration',
 PutAppValidationConfiguration = 'sms:PutAppValidationConfiguration',
 SendMessage = 'sms:SendMessage',
 StartAppReplication = 'sms:StartAppReplication',
 StartOnDemandAppReplication = 'sms:StartOnDemandAppReplication',
 StartOnDemandReplicationRun = 'sms:StartOnDemandReplicationRun',
 StopAppReplication = 'sms:StopAppReplication',
 TerminateApp = 'sms:TerminateApp',
 UpdateApp = 'sms:UpdateApp',
 UpdateReplicationJob = 'sms:UpdateReplicationJob',

}