
export enum snowball {
 All = 'snowball:*',
 Cancel = 'snowball:Cancel*',
 Create = 'snowball:Create*',
 Describe = 'snowball:Describe*',
 Get = 'snowball:Get*',
 List = 'snowball:List*',
 Update = 'snowball:Update*',
 CancelCluster = 'snowball:CancelCluster',
 CancelJob = 'snowball:CancelJob',
 CreateAddress = 'snowball:CreateAddress',
 CreateCluster = 'snowball:CreateCluster',
 CreateJob = 'snowball:CreateJob',
 DescribeAddress = 'snowball:DescribeAddress',
 DescribeAddresses = 'snowball:DescribeAddresses',
 DescribeCluster = 'snowball:DescribeCluster',
 DescribeJob = 'snowball:DescribeJob',
 GetJobManifest = 'snowball:GetJobManifest',
 GetJobUnlockCode = 'snowball:GetJobUnlockCode',
 GetSnowballUsage = 'snowball:GetSnowballUsage',
 ListClusterJobs = 'snowball:ListClusterJobs',
 ListClusters = 'snowball:ListClusters',
 ListJobs = 'snowball:ListJobs',
 UpdateCluster = 'snowball:UpdateCluster',
 UpdateJob = 'snowball:UpdateJob',

}