
export enum sqs {
 All = 'sqs:*',
 Change = 'sqs:Change*',
 Delete = 'sqs:Delete*',
 Get = 'sqs:Get*',
 List = 'sqs:List*',
 Send = 'sqs:Send*',
 AddPermission = 'sqs:AddPermission',
 ChangeMessageVisibility = 'sqs:ChangeMessageVisibility',
 ChangeMessageVisibilityBatch = 'sqs:ChangeMessageVisibilityBatch',
 CreateQueue = 'sqs:CreateQueue',
 DeleteMessage = 'sqs:DeleteMessage',
 DeleteMessageBatch = 'sqs:DeleteMessageBatch',
 DeleteQueue = 'sqs:DeleteQueue',
 GetQueueAttributes = 'sqs:GetQueueAttributes',
 GetQueueUrl = 'sqs:GetQueueUrl',
 ListDeadLetterSourceQueues = 'sqs:ListDeadLetterSourceQueues',
 ListQueueTags = 'sqs:ListQueueTags',
 ListQueues = 'sqs:ListQueues',
 PurgeQueue = 'sqs:PurgeQueue',
 ReceiveMessage = 'sqs:ReceiveMessage',
 RemovePermission = 'sqs:RemovePermission',
 SendMessage = 'sqs:SendMessage',
 SendMessageBatch = 'sqs:SendMessageBatch',
 SetQueueAttributes = 'sqs:SetQueueAttributes',
 TagQueue = 'sqs:TagQueue',
 UntagQueue = 'sqs:UntagQueue',

}