
export enum support {
 AddAttachmentsToSet = 'support:AddAttachmentsToSet',
 AddCommunicationToCase = 'support:AddCommunicationToCase',
 CreateCase = 'support:CreateCase',
 DescribeAttachment = 'support:DescribeAttachment',
 DescribeCaseAttributes = 'support:DescribeCaseAttributes',
 DescribeCases = 'support:DescribeCases',
 DescribeCommunications = 'support:DescribeCommunications',
 DescribeIssueTypes = 'support:DescribeIssueTypes',
 DescribeServices = 'support:DescribeServices',
 DescribeSeverityLevels = 'support:DescribeSeverityLevels',
 DescribeSupportLevel = 'support:DescribeSupportLevel',
 DescribeTrustedAdvisorCheckRefreshStatuses = 'support:DescribeTrustedAdvisorCheckRefreshStatuses',
 DescribeTrustedAdvisorCheckResult = 'support:DescribeTrustedAdvisorCheckResult',
 DescribeTrustedAdvisorCheckSummaries = 'support:DescribeTrustedAdvisorCheckSummaries',
 DescribeTrustedAdvisorChecks = 'support:DescribeTrustedAdvisorChecks',
 InitiateCallForCase = 'support:InitiateCallForCase',
 InitiateChatForCase = 'support:InitiateChatForCase',
 PutCaseAttributes = 'support:PutCaseAttributes',
 RateCaseCommunication = 'support:RateCaseCommunication',
 RefreshTrustedAdvisorCheck = 'support:RefreshTrustedAdvisorCheck',
 ResolveCase = 'support:ResolveCase',
 SearchForCases = 'support:SearchForCases',

}