
export enum timestream {
 All = 'timestream:*',
 Create = 'timestream:Create*',
 Delete = 'timestream:Delete*',
 Describe = 'timestream:Describe*',
 List = 'timestream:List*',
 Select = 'timestream:Select*',
 Update = 'timestream:Update*',
 CancelQuery = 'timestream:CancelQuery',
 CreateDatabase = 'timestream:CreateDatabase',
 CreateTable = 'timestream:CreateTable',
 DeleteDatabase = 'timestream:DeleteDatabase',
 DeleteTable = 'timestream:DeleteTable',
 DescribeDatabase = 'timestream:DescribeDatabase',
 DescribeEndpoints = 'timestream:DescribeEndpoints',
 DescribeTable = 'timestream:DescribeTable',
 ListDatabases = 'timestream:ListDatabases',
 ListMeasures = 'timestream:ListMeasures',
 ListTables = 'timestream:ListTables',
 ListTagsForResource = 'timestream:ListTagsForResource',
 Select = 'timestream:Select',
 SelectValues = 'timestream:SelectValues',
 TagResource = 'timestream:TagResource',
 UntagResource = 'timestream:UntagResource',
 UpdateDatabase = 'timestream:UpdateDatabase',
 UpdateTable = 'timestream:UpdateTable',
 WriteRecords = 'timestream:WriteRecords',

}