
export enum transcribe {
 All = 'transcribe:*',
 Create = 'transcribe:Create*',
 Delete = 'transcribe:Delete*',
 Get = 'transcribe:Get*',
 List = 'transcribe:List*',
 Start = 'transcribe:Start*',
 Update = 'transcribe:Update*',
 CreateLanguageModel = 'transcribe:CreateLanguageModel',
 CreateMedicalVocabulary = 'transcribe:CreateMedicalVocabulary',
 CreateVocabulary = 'transcribe:CreateVocabulary',
 CreateVocabularyFilter = 'transcribe:CreateVocabularyFilter',
 DeleteLanguageModel = 'transcribe:DeleteLanguageModel',
 DeleteMedicalTranscriptionJob = 'transcribe:DeleteMedicalTranscriptionJob',
 DeleteMedicalVocabulary = 'transcribe:DeleteMedicalVocabulary',
 DeleteTranscriptionJob = 'transcribe:DeleteTranscriptionJob',
 DeleteVocabulary = 'transcribe:DeleteVocabulary',
 DeleteVocabularyFilter = 'transcribe:DeleteVocabularyFilter',
 DescribeLanguageModel = 'transcribe:DescribeLanguageModel',
 GetMedicalTranscriptionJob = 'transcribe:GetMedicalTranscriptionJob',
 GetMedicalVocabulary = 'transcribe:GetMedicalVocabulary',
 GetTranscriptionJob = 'transcribe:GetTranscriptionJob',
 GetVocabulary = 'transcribe:GetVocabulary',
 GetVocabularyFilter = 'transcribe:GetVocabularyFilter',
 ListLanguageModels = 'transcribe:ListLanguageModels',
 ListMedicalTranscriptionJobs = 'transcribe:ListMedicalTranscriptionJobs',
 ListMedicalVocabularies = 'transcribe:ListMedicalVocabularies',
 ListTranscriptionJobs = 'transcribe:ListTranscriptionJobs',
 ListVocabularies = 'transcribe:ListVocabularies',
 ListVocabularyFilters = 'transcribe:ListVocabularyFilters',
 StartMedicalStreamTranscription = 'transcribe:StartMedicalStreamTranscription',
 StartMedicalStreamTranscriptionWebSocket = 'transcribe:StartMedicalStreamTranscriptionWebSocket',
 StartMedicalTranscriptionJob = 'transcribe:StartMedicalTranscriptionJob',
 StartStreamTranscription = 'transcribe:StartStreamTranscription',
 StartStreamTranscriptionWebSocket = 'transcribe:StartStreamTranscriptionWebSocket',
 StartTranscriptionJob = 'transcribe:StartTranscriptionJob',
 UpdateMedicalVocabulary = 'transcribe:UpdateMedicalVocabulary',
 UpdateVocabulary = 'transcribe:UpdateVocabulary',
 UpdateVocabularyFilter = 'transcribe:UpdateVocabularyFilter',

}