
export enum wafv2 {
 AssociateWebACL = 'wafv2:AssociateWebACL',
 CheckCapacity = 'wafv2:CheckCapacity',
 CreateIPSet = 'wafv2:CreateIPSet',
 CreateRegexPatternSet = 'wafv2:CreateRegexPatternSet',
 CreateRuleGroup = 'wafv2:CreateRuleGroup',
 CreateWebACL = 'wafv2:CreateWebACL',
 DeleteFirewallManagerRuleGroups = 'wafv2:DeleteFirewallManagerRuleGroups',
 DeleteIPSet = 'wafv2:DeleteIPSet',
 DeleteLoggingConfiguration = 'wafv2:DeleteLoggingConfiguration',
 DeletePermissionPolicy = 'wafv2:DeletePermissionPolicy',
 DeleteRegexPatternSet = 'wafv2:DeleteRegexPatternSet',
 DeleteRuleGroup = 'wafv2:DeleteRuleGroup',
 DeleteWebACL = 'wafv2:DeleteWebACL',
 DescribeManagedRuleGroup = 'wafv2:DescribeManagedRuleGroup',
 DisassociateFirewallManager = 'wafv2:DisassociateFirewallManager',
 DisassociateWebACL = 'wafv2:DisassociateWebACL',
 GetIPSet = 'wafv2:GetIPSet',
 GetLoggingConfiguration = 'wafv2:GetLoggingConfiguration',
 GetPermissionPolicy = 'wafv2:GetPermissionPolicy',
 GetRateBasedStatementManagedKeys = 'wafv2:GetRateBasedStatementManagedKeys',
 GetRegexPatternSet = 'wafv2:GetRegexPatternSet',
 GetRuleGroup = 'wafv2:GetRuleGroup',
 GetSampledRequests = 'wafv2:GetSampledRequests',
 GetWebACL = 'wafv2:GetWebACL',
 GetWebACLForResource = 'wafv2:GetWebACLForResource',
 ListAvailableManagedRuleGroups = 'wafv2:ListAvailableManagedRuleGroups',
 ListIPSets = 'wafv2:ListIPSets',
 ListLoggingConfigurations = 'wafv2:ListLoggingConfigurations',
 ListRegexPatternSets = 'wafv2:ListRegexPatternSets',
 ListResourcesForWebACL = 'wafv2:ListResourcesForWebACL',
 ListRuleGroups = 'wafv2:ListRuleGroups',
 ListTagsForResource = 'wafv2:ListTagsForResource',
 ListWebACLs = 'wafv2:ListWebACLs',
 PutFirewallManagerRuleGroups = 'wafv2:PutFirewallManagerRuleGroups',
 PutLoggingConfiguration = 'wafv2:PutLoggingConfiguration',
 PutPermissionPolicy = 'wafv2:PutPermissionPolicy',
 TagResource = 'wafv2:TagResource',
 UntagResource = 'wafv2:UntagResource',
 UpdateIPSet = 'wafv2:UpdateIPSet',
 UpdateRegexPatternSet = 'wafv2:UpdateRegexPatternSet',
 UpdateRuleGroup = 'wafv2:UpdateRuleGroup',
 UpdateWebACL = 'wafv2:UpdateWebACL',

}