
export enum wellarchitected {
 All = 'wellarchitected:*',
 Create = 'wellarchitected:Create*',
 Delete = 'wellarchitected:Delete*',
 Get = 'wellarchitected:Get*',
 List = 'wellarchitected:List*',
 Update = 'wellarchitected:Update*',
 AssociateLenses = 'wellarchitected:AssociateLenses',
 CreateMilestone = 'wellarchitected:CreateMilestone',
 CreateWorkload = 'wellarchitected:CreateWorkload',
 CreateWorkloadShare = 'wellarchitected:CreateWorkloadShare',
 DeleteWorkload = 'wellarchitected:DeleteWorkload',
 DeleteWorkloadShare = 'wellarchitected:DeleteWorkloadShare',
 DisassociateLenses = 'wellarchitected:DisassociateLenses',
 GetAnswer = 'wellarchitected:GetAnswer',
 GetLensReview = 'wellarchitected:GetLensReview',
 GetLensReviewReport = 'wellarchitected:GetLensReviewReport',
 GetLensVersionDifference = 'wellarchitected:GetLensVersionDifference',
 GetMilestone = 'wellarchitected:GetMilestone',
 GetWorkload = 'wellarchitected:GetWorkload',
 ListAnswers = 'wellarchitected:ListAnswers',
 ListLensReviewImprovements = 'wellarchitected:ListLensReviewImprovements',
 ListLensReviews = 'wellarchitected:ListLensReviews',
 ListLenses = 'wellarchitected:ListLenses',
 ListMilestones = 'wellarchitected:ListMilestones',
 ListNotifications = 'wellarchitected:ListNotifications',
 ListShareInvitations = 'wellarchitected:ListShareInvitations',
 ListWorkloadShares = 'wellarchitected:ListWorkloadShares',
 ListWorkloads = 'wellarchitected:ListWorkloads',
 UpdateAnswer = 'wellarchitected:UpdateAnswer',
 UpdateLensReview = 'wellarchitected:UpdateLensReview',
 UpdateShareInvitation = 'wellarchitected:UpdateShareInvitation',
 UpdateWorkload = 'wellarchitected:UpdateWorkload',
 UpdateWorkloadShare = 'wellarchitected:UpdateWorkloadShare',
 UpgradeLensReview = 'wellarchitected:UpgradeLensReview',

}