
export enum workspaces {
 All = 'workspaces:*',
 Create = 'workspaces:Create*',
 Delete = 'workspaces:Delete*',
 Describe = 'workspaces:Describe*',
 Modify = 'workspaces:Modify*',
 AssociateIpGroups = 'workspaces:AssociateIpGroups',
 AuthorizeIpRules = 'workspaces:AuthorizeIpRules',
 CreateIpGroup = 'workspaces:CreateIpGroup',
 CreateTags = 'workspaces:CreateTags',
 CreateWorkspaces = 'workspaces:CreateWorkspaces',
 DeleteIpGroup = 'workspaces:DeleteIpGroup',
 DeleteTags = 'workspaces:DeleteTags',
 DeleteWorkspaceImage = 'workspaces:DeleteWorkspaceImage',
 DescribeAccount = 'workspaces:DescribeAccount',
 DescribeAccountModifications = 'workspaces:DescribeAccountModifications',
 DescribeClientProperties = 'workspaces:DescribeClientProperties',
 DescribeIpGroups = 'workspaces:DescribeIpGroups',
 DescribeTags = 'workspaces:DescribeTags',
 DescribeWorkspaceBundles = 'workspaces:DescribeWorkspaceBundles',
 DescribeWorkspaceDirectories = 'workspaces:DescribeWorkspaceDirectories',
 DescribeWorkspaceImages = 'workspaces:DescribeWorkspaceImages',
 DescribeWorkspaces = 'workspaces:DescribeWorkspaces',
 DescribeWorkspacesConnectionStatus = 'workspaces:DescribeWorkspacesConnectionStatus',
 DisassociateIpGroups = 'workspaces:DisassociateIpGroups',
 ImportWorkspaceImage = 'workspaces:ImportWorkspaceImage',
 ListAvailableManagementCidrRanges = 'workspaces:ListAvailableManagementCidrRanges',
 ModifyAccount = 'workspaces:ModifyAccount',
 ModifyClientProperties = 'workspaces:ModifyClientProperties',
 ModifyWorkspaceProperties = 'workspaces:ModifyWorkspaceProperties',
 ModifyWorkspaceState = 'workspaces:ModifyWorkspaceState',
 RebootWorkspaces = 'workspaces:RebootWorkspaces',
 RebuildWorkspaces = 'workspaces:RebuildWorkspaces',
 RevokeIpRules = 'workspaces:RevokeIpRules',
 StartWorkspaces = 'workspaces:StartWorkspaces',
 StopWorkspaces = 'workspaces:StopWorkspaces',
 TerminateWorkspaces = 'workspaces:TerminateWorkspaces',
 UpdateRulesOfIpGroup = 'workspaces:UpdateRulesOfIpGroup',

}