
export enum worklink {
 AssociateDomain = 'worklink:AssociateDomain',
 AssociateWebsiteAuthorizationProvider = 'worklink:AssociateWebsiteAuthorizationProvider',
 AssociateWebsiteCertificateAuthority = 'worklink:AssociateWebsiteCertificateAuthority',
 CreateFleet = 'worklink:CreateFleet',
 DeleteFleet = 'worklink:DeleteFleet',
 DescribeAuditStreamConfiguration = 'worklink:DescribeAuditStreamConfiguration',
 DescribeCompanyNetworkConfiguration = 'worklink:DescribeCompanyNetworkConfiguration',
 DescribeDevice = 'worklink:DescribeDevice',
 DescribeDevicePolicyConfiguration = 'worklink:DescribeDevicePolicyConfiguration',
 DescribeDomain = 'worklink:DescribeDomain',
 DescribeFleetMetadata = 'worklink:DescribeFleetMetadata',
 DescribeIdentityProviderConfiguration = 'worklink:DescribeIdentityProviderConfiguration',
 DescribeWebsiteCertificateAuthority = 'worklink:DescribeWebsiteCertificateAuthority',
 DisassociateDomain = 'worklink:DisassociateDomain',
 DisassociateWebsiteAuthorizationProvider = 'worklink:DisassociateWebsiteAuthorizationProvider',
 DisassociateWebsiteCertificateAuthority = 'worklink:DisassociateWebsiteCertificateAuthority',
 ListDevices = 'worklink:ListDevices',
 ListDomains = 'worklink:ListDomains',
 ListFleets = 'worklink:ListFleets',
 ListTagsForResource = 'worklink:ListTagsForResource',
 ListWebsiteAuthorizationProviders = 'worklink:ListWebsiteAuthorizationProviders',
 ListWebsiteCertificateAuthorities = 'worklink:ListWebsiteCertificateAuthorities',
 RestoreDomainAccess = 'worklink:RestoreDomainAccess',
 RevokeDomainAccess = 'worklink:RevokeDomainAccess',
 SearchEntity = 'worklink:SearchEntity',
 SignOutUser = 'worklink:SignOutUser',
 TagResource = 'worklink:TagResource',
 UntagResource = 'worklink:UntagResource',
 UpdateAuditStreamConfiguration = 'worklink:UpdateAuditStreamConfiguration',
 UpdateCompanyNetworkConfiguration = 'worklink:UpdateCompanyNetworkConfiguration',
 UpdateDevicePolicyConfiguration = 'worklink:UpdateDevicePolicyConfiguration',
 UpdateDomainMetadata = 'worklink:UpdateDomainMetadata',
 UpdateFleetMetadata = 'worklink:UpdateFleetMetadata',
 UpdateIdentityProviderConfiguration = 'worklink:UpdateIdentityProviderConfiguration',

}