
export enum xray {
 BatchGetTraces = 'xray:BatchGetTraces',
 CreateGroup = 'xray:CreateGroup',
 CreateSamplingRule = 'xray:CreateSamplingRule',
 DeleteGroup = 'xray:DeleteGroup',
 DeleteSamplingRule = 'xray:DeleteSamplingRule',
 GetEncryptionConfig = 'xray:GetEncryptionConfig',
 GetGroup = 'xray:GetGroup',
 GetGroups = 'xray:GetGroups',
 GetInsight = 'xray:GetInsight',
 GetInsightEvents = 'xray:GetInsightEvents',
 GetInsightImpactGraph = 'xray:GetInsightImpactGraph',
 GetInsightSummaries = 'xray:GetInsightSummaries',
 GetSamplingRules = 'xray:GetSamplingRules',
 GetSamplingStatisticSummaries = 'xray:GetSamplingStatisticSummaries',
 GetSamplingTargets = 'xray:GetSamplingTargets',
 GetServiceGraph = 'xray:GetServiceGraph',
 GetTimeSeriesServiceStatistics = 'xray:GetTimeSeriesServiceStatistics',
 GetTraceGraph = 'xray:GetTraceGraph',
 GetTraceSummaries = 'xray:GetTraceSummaries',
 ListTagsForResource = 'xray:ListTagsForResource',
 PutEncryptionConfig = 'xray:PutEncryptionConfig',
 PutTelemetryRecords = 'xray:PutTelemetryRecords',
 PutTraceSegments = 'xray:PutTraceSegments',
 TagResource = 'xray:TagResource',
 UntagResource = 'xray:UntagResource',
 UpdateGroup = 'xray:UpdateGroup',
 UpdateSamplingRule = 'xray:UpdateSamplingRule',

}